package com.xiaochong.loan.background.entity.po;

public class AttributionInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_attribution_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_attribution_info.mobile_num
     *
     * @mbggenerated
     */
    private String mobileNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_attribution_info.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_attribution_info.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_attribution_info.carrier
     *
     * @mbggenerated
     */
    private String carrier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_attribution_info.area_code
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_attribution_info.post_code
     *
     * @mbggenerated
     */
    private String postCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_attribution_info.id
     *
     * @return the value of loan_attribution_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_attribution_info.id
     *
     * @param id the value for loan_attribution_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_attribution_info.mobile_num
     *
     * @return the value of loan_attribution_info.mobile_num
     *
     * @mbggenerated
     */
    public String getMobileNum() {
        return mobileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_attribution_info.mobile_num
     *
     * @param mobileNum the value for loan_attribution_info.mobile_num
     *
     * @mbggenerated
     */
    public void setMobileNum(String mobileNum) {
        this.mobileNum = mobileNum == null ? null : mobileNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_attribution_info.city
     *
     * @return the value of loan_attribution_info.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_attribution_info.city
     *
     * @param city the value for loan_attribution_info.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_attribution_info.area
     *
     * @return the value of loan_attribution_info.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_attribution_info.area
     *
     * @param area the value for loan_attribution_info.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_attribution_info.carrier
     *
     * @return the value of loan_attribution_info.carrier
     *
     * @mbggenerated
     */
    public String getCarrier() {
        return carrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_attribution_info.carrier
     *
     * @param carrier the value for loan_attribution_info.carrier
     *
     * @mbggenerated
     */
    public void setCarrier(String carrier) {
        this.carrier = carrier == null ? null : carrier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_attribution_info.area_code
     *
     * @return the value of loan_attribution_info.area_code
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_attribution_info.area_code
     *
     * @param areaCode the value for loan_attribution_info.area_code
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_attribution_info.post_code
     *
     * @return the value of loan_attribution_info.post_code
     *
     * @mbggenerated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_attribution_info.post_code
     *
     * @param postCode the value for loan_attribution_info.post_code
     *
     * @mbggenerated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }
}