package com.xiaochong.loan.background.entity.po;

public class AuthLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_auth_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_auth_log.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_auth_log.order_num
     *
     * @mbggenerated
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_auth_log.data
     *
     * @mbggenerated
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_auth_log.error_message
     *
     * @mbggenerated
     */
    private String errorMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_auth_log.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_auth_log.result
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_auth_log.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_auth_log.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_auth_log.id
     *
     * @return the value of loan_auth_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_auth_log.id
     *
     * @param id the value for loan_auth_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_auth_log.id_card
     *
     * @return the value of loan_auth_log.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_auth_log.id_card
     *
     * @param idCard the value for loan_auth_log.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_auth_log.order_num
     *
     * @return the value of loan_auth_log.order_num
     *
     * @mbggenerated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_auth_log.order_num
     *
     * @param orderNum the value for loan_auth_log.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_auth_log.data
     *
     * @return the value of loan_auth_log.data
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_auth_log.data
     *
     * @param data the value for loan_auth_log.data
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_auth_log.error_message
     *
     * @return the value of loan_auth_log.error_message
     *
     * @mbggenerated
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_auth_log.error_message
     *
     * @param errorMessage the value for loan_auth_log.error_message
     *
     * @mbggenerated
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage == null ? null : errorMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_auth_log.type
     *
     * @return the value of loan_auth_log.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_auth_log.type
     *
     * @param type the value for loan_auth_log.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_auth_log.result
     *
     * @return the value of loan_auth_log.result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_auth_log.result
     *
     * @param result the value for loan_auth_log.result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_auth_log.create_time
     *
     * @return the value of loan_auth_log.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_auth_log.create_time
     *
     * @param createTime the value for loan_auth_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_auth_log.update_time
     *
     * @return the value of loan_auth_log.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_auth_log.update_time
     *
     * @param updateTime the value for loan_auth_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}