package com.xiaochong.loan.background.entity.po;

import java.util.Date;

public class ContactInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contact_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contact_info.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contact_info.order_token
     *
     * @mbggenerated
     */
    private String orderToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contact_info.merch_id
     *
     * @mbggenerated
     */
    private Integer merchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contact_info.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contact_info.relation
     *
     * @mbggenerated
     */
    private String relation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contact_info.relation_name
     *
     * @mbggenerated
     */
    private String relationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contact_info.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contact_info.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contact_info.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contact_info.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contact_info.id
     *
     * @return the value of loan_contact_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contact_info.id
     *
     * @param id the value for loan_contact_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contact_info.order_no
     *
     * @return the value of loan_contact_info.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contact_info.order_no
     *
     * @param orderNo the value for loan_contact_info.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contact_info.order_token
     *
     * @return the value of loan_contact_info.order_token
     *
     * @mbggenerated
     */
    public String getOrderToken() {
        return orderToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contact_info.order_token
     *
     * @param orderToken the value for loan_contact_info.order_token
     *
     * @mbggenerated
     */
    public void setOrderToken(String orderToken) {
        this.orderToken = orderToken == null ? null : orderToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contact_info.merch_id
     *
     * @return the value of loan_contact_info.merch_id
     *
     * @mbggenerated
     */
    public Integer getMerchId() {
        return merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contact_info.merch_id
     *
     * @param merchId the value for loan_contact_info.merch_id
     *
     * @mbggenerated
     */
    public void setMerchId(Integer merchId) {
        this.merchId = merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contact_info.id_card
     *
     * @return the value of loan_contact_info.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contact_info.id_card
     *
     * @param idCard the value for loan_contact_info.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contact_info.relation
     *
     * @return the value of loan_contact_info.relation
     *
     * @mbggenerated
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contact_info.relation
     *
     * @param relation the value for loan_contact_info.relation
     *
     * @mbggenerated
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contact_info.relation_name
     *
     * @return the value of loan_contact_info.relation_name
     *
     * @mbggenerated
     */
    public String getRelationName() {
        return relationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contact_info.relation_name
     *
     * @param relationName the value for loan_contact_info.relation_name
     *
     * @mbggenerated
     */
    public void setRelationName(String relationName) {
        this.relationName = relationName == null ? null : relationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contact_info.real_name
     *
     * @return the value of loan_contact_info.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contact_info.real_name
     *
     * @param realName the value for loan_contact_info.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contact_info.phone
     *
     * @return the value of loan_contact_info.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contact_info.phone
     *
     * @param phone the value for loan_contact_info.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contact_info.updatetime
     *
     * @return the value of loan_contact_info.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contact_info.updatetime
     *
     * @param updatetime the value for loan_contact_info.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contact_info.createtime
     *
     * @return the value of loan_contact_info.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contact_info.createtime
     *
     * @param createtime the value for loan_contact_info.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}