package com.xiaochong.loan.background.entity.po;

public class EducationInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_education_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_education_info.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_education_info.identity_card
     *
     * @mbggenerated
     */
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_education_info.graduate_school
     *
     * @mbggenerated
     */
    private String graduateSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_education_info.education_background
     *
     * @mbggenerated
     */
    private String educationBackground;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_education_info.matriculation_time
     *
     * @mbggenerated
     */
    private String matriculationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_education_info.profession
     *
     * @mbggenerated
     */
    private String profession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_education_info.graduation_time
     *
     * @mbggenerated
     */
    private String graduationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_education_info.graduation_conclusion
     *
     * @mbggenerated
     */
    private String graduationConclusion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_education_info.education_type
     *
     * @mbggenerated
     */
    private String educationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_education_info.query_result
     *
     * @mbggenerated
     */
    private String queryResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_education_info.id
     *
     * @return the value of loan_education_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_education_info.id
     *
     * @param id the value for loan_education_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_education_info.realname
     *
     * @return the value of loan_education_info.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_education_info.realname
     *
     * @param realname the value for loan_education_info.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_education_info.identity_card
     *
     * @return the value of loan_education_info.identity_card
     *
     * @mbggenerated
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_education_info.identity_card
     *
     * @param identityCard the value for loan_education_info.identity_card
     *
     * @mbggenerated
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard == null ? null : identityCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_education_info.graduate_school
     *
     * @return the value of loan_education_info.graduate_school
     *
     * @mbggenerated
     */
    public String getGraduateSchool() {
        return graduateSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_education_info.graduate_school
     *
     * @param graduateSchool the value for loan_education_info.graduate_school
     *
     * @mbggenerated
     */
    public void setGraduateSchool(String graduateSchool) {
        this.graduateSchool = graduateSchool == null ? null : graduateSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_education_info.education_background
     *
     * @return the value of loan_education_info.education_background
     *
     * @mbggenerated
     */
    public String getEducationBackground() {
        return educationBackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_education_info.education_background
     *
     * @param educationBackground the value for loan_education_info.education_background
     *
     * @mbggenerated
     */
    public void setEducationBackground(String educationBackground) {
        this.educationBackground = educationBackground == null ? null : educationBackground.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_education_info.matriculation_time
     *
     * @return the value of loan_education_info.matriculation_time
     *
     * @mbggenerated
     */
    public String getMatriculationTime() {
        return matriculationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_education_info.matriculation_time
     *
     * @param matriculationTime the value for loan_education_info.matriculation_time
     *
     * @mbggenerated
     */
    public void setMatriculationTime(String matriculationTime) {
        this.matriculationTime = matriculationTime == null ? null : matriculationTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_education_info.profession
     *
     * @return the value of loan_education_info.profession
     *
     * @mbggenerated
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_education_info.profession
     *
     * @param profession the value for loan_education_info.profession
     *
     * @mbggenerated
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_education_info.graduation_time
     *
     * @return the value of loan_education_info.graduation_time
     *
     * @mbggenerated
     */
    public String getGraduationTime() {
        return graduationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_education_info.graduation_time
     *
     * @param graduationTime the value for loan_education_info.graduation_time
     *
     * @mbggenerated
     */
    public void setGraduationTime(String graduationTime) {
        this.graduationTime = graduationTime == null ? null : graduationTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_education_info.graduation_conclusion
     *
     * @return the value of loan_education_info.graduation_conclusion
     *
     * @mbggenerated
     */
    public String getGraduationConclusion() {
        return graduationConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_education_info.graduation_conclusion
     *
     * @param graduationConclusion the value for loan_education_info.graduation_conclusion
     *
     * @mbggenerated
     */
    public void setGraduationConclusion(String graduationConclusion) {
        this.graduationConclusion = graduationConclusion == null ? null : graduationConclusion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_education_info.education_type
     *
     * @return the value of loan_education_info.education_type
     *
     * @mbggenerated
     */
    public String getEducationType() {
        return educationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_education_info.education_type
     *
     * @param educationType the value for loan_education_info.education_type
     *
     * @mbggenerated
     */
    public void setEducationType(String educationType) {
        this.educationType = educationType == null ? null : educationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_education_info.query_result
     *
     * @return the value of loan_education_info.query_result
     *
     * @mbggenerated
     */
    public String getQueryResult() {
        return queryResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_education_info.query_result
     *
     * @param queryResult the value for loan_education_info.query_result
     *
     * @mbggenerated
     */
    public void setQueryResult(String queryResult) {
        this.queryResult = queryResult == null ? null : queryResult.trim();
    }
}