package com.xiaochong.loan.background.entity.po;

public class FlowOption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_flow_option.id
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_flow_option.flow_no
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    private String flowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_flow_option.flow_option_no
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    private String flowOptionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_flow_option.option_name
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    private String optionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_flow_option.option_code
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    private String optionDesc;

    /**
     * 字段类型  用户信息","01 学历信息","02 手机信息","03 用户查询信息","04
     * 联系人信息","05 通讯黑名单信息","06 近6个月联系人","07 借贷过往记录","08
     * 不良扫描记录","09 行业关注名单","10
     */
    private String optionType;

    public String getOptionType() {
        return optionType;
    }

    public void setOptionType(String optionType) {
        this.optionType = optionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_flow_option.id
     *
     * @return the value of loan_flow_option.id
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_flow_option.id
     *
     * @param id the value for loan_flow_option.id
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_flow_option.flow_no
     *
     * @return the value of loan_flow_option.flow_no
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_flow_option.flow_no
     *
     * @param flowNo the value for loan_flow_option.flow_no
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo == null ? null : flowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_flow_option.flow_option_no
     *
     * @return the value of loan_flow_option.flow_option_no
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    public String getFlowOptionNo() {
        return flowOptionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_flow_option.flow_option_no
     *
     * @param flowOptionNo the value for loan_flow_option.flow_option_no
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    public void setFlowOptionNo(String flowOptionNo) {
        this.flowOptionNo = flowOptionNo == null ? null : flowOptionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_flow_option.option_name
     *
     * @return the value of loan_flow_option.option_name
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_flow_option.option_name
     *
     * @param optionName the value for loan_flow_option.option_name
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName == null ? null : optionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_flow_option.option_code
     *
     * @return the value of loan_flow_option.option_code
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    public String getOptionDesc() {
        return optionDesc;
    }

    public void setOptionDesc(String optionDesc) {
        this.optionDesc = optionDesc;
    }
}