package com.xiaochong.loan.background.entity.po;

public class MerchantFlowOption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchant_flow_option.id
     *
     * @mbggenerated Sat Aug 12 10:49:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchant_flow_option.merch_id
     *
     * @mbggenerated Sat Aug 12 10:49:32 CST 2017
     */
    private Integer merchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchant_flow_option.flow_no
     *
     * @mbggenerated Sat Aug 12 10:49:32 CST 2017
     */
    private String flowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchant_flow_option.flow_option_no
     *
     * @mbggenerated Sat Aug 12 10:49:32 CST 2017
     */
    private String flowOptionNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchant_flow_option.id
     *
     * @return the value of loan_merchant_flow_option.id
     *
     * @mbggenerated Sat Aug 12 10:49:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchant_flow_option.id
     *
     * @param id the value for loan_merchant_flow_option.id
     *
     * @mbggenerated Sat Aug 12 10:49:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchant_flow_option.merch_id
     *
     * @return the value of loan_merchant_flow_option.merch_id
     *
     * @mbggenerated Sat Aug 12 10:49:32 CST 2017
     */
    public Integer getMerchId() {
        return merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchant_flow_option.merch_id
     *
     * @param merchId the value for loan_merchant_flow_option.merch_id
     *
     * @mbggenerated Sat Aug 12 10:49:32 CST 2017
     */
    public void setMerchId(Integer merchId) {
        this.merchId = merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchant_flow_option.flow_no
     *
     * @return the value of loan_merchant_flow_option.flow_no
     *
     * @mbggenerated Sat Aug 12 10:49:32 CST 2017
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchant_flow_option.flow_no
     *
     * @param flowNo the value for loan_merchant_flow_option.flow_no
     *
     * @mbggenerated Sat Aug 12 10:49:32 CST 2017
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo == null ? null : flowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchant_flow_option.flow_option_no
     *
     * @return the value of loan_merchant_flow_option.flow_option_no
     *
     * @mbggenerated Sat Aug 12 10:49:32 CST 2017
     */
    public String getFlowOptionNo() {
        return flowOptionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchant_flow_option.flow_option_no
     *
     * @param flowOptionNo the value for loan_merchant_flow_option.flow_option_no
     *
     * @mbggenerated Sat Aug 12 10:49:32 CST 2017
     */
    public void setFlowOptionNo(String flowOptionNo) {
        this.flowOptionNo = flowOptionNo == null ? null : flowOptionNo.trim();
    }
}