package com.xiaochong.loan.background.entity.po;

public class MerchantinfoCopy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchantinfo_copy.toid
     *
     * @mbggenerated
     */
    private String toid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchantinfo_copy.merchant_name
     *
     * @mbggenerated
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchantinfo_copy.link_man
     *
     * @mbggenerated
     */
    private String linkMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchantinfo_copy.link_mobile
     *
     * @mbggenerated
     */
    private String linkMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchantinfo_copy.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchantinfo_copy.industry
     *
     * @mbggenerated
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchantinfo_copy.scale
     *
     * @mbggenerated
     */
    private String scale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchantinfo_copy.certificate_name
     *
     * @mbggenerated
     */
    private String certificateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchantinfo_copy.certificate_url
     *
     * @mbggenerated
     */
    private String certificateUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchantinfo_copy.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchantinfo_copy.createtime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchantinfo_copy.updatetime
     *
     * @mbggenerated
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchantinfo_copy.toid
     *
     * @return the value of loan_merchantinfo_copy.toid
     *
     * @mbggenerated
     */
    public String getToid() {
        return toid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchantinfo_copy.toid
     *
     * @param toid the value for loan_merchantinfo_copy.toid
     *
     * @mbggenerated
     */
    public void setToid(String toid) {
        this.toid = toid == null ? null : toid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchantinfo_copy.merchant_name
     *
     * @return the value of loan_merchantinfo_copy.merchant_name
     *
     * @mbggenerated
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchantinfo_copy.merchant_name
     *
     * @param merchantName the value for loan_merchantinfo_copy.merchant_name
     *
     * @mbggenerated
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchantinfo_copy.link_man
     *
     * @return the value of loan_merchantinfo_copy.link_man
     *
     * @mbggenerated
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchantinfo_copy.link_man
     *
     * @param linkMan the value for loan_merchantinfo_copy.link_man
     *
     * @mbggenerated
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan == null ? null : linkMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchantinfo_copy.link_mobile
     *
     * @return the value of loan_merchantinfo_copy.link_mobile
     *
     * @mbggenerated
     */
    public String getLinkMobile() {
        return linkMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchantinfo_copy.link_mobile
     *
     * @param linkMobile the value for loan_merchantinfo_copy.link_mobile
     *
     * @mbggenerated
     */
    public void setLinkMobile(String linkMobile) {
        this.linkMobile = linkMobile == null ? null : linkMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchantinfo_copy.address
     *
     * @return the value of loan_merchantinfo_copy.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchantinfo_copy.address
     *
     * @param address the value for loan_merchantinfo_copy.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchantinfo_copy.industry
     *
     * @return the value of loan_merchantinfo_copy.industry
     *
     * @mbggenerated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchantinfo_copy.industry
     *
     * @param industry the value for loan_merchantinfo_copy.industry
     *
     * @mbggenerated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchantinfo_copy.scale
     *
     * @return the value of loan_merchantinfo_copy.scale
     *
     * @mbggenerated
     */
    public String getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchantinfo_copy.scale
     *
     * @param scale the value for loan_merchantinfo_copy.scale
     *
     * @mbggenerated
     */
    public void setScale(String scale) {
        this.scale = scale == null ? null : scale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchantinfo_copy.certificate_name
     *
     * @return the value of loan_merchantinfo_copy.certificate_name
     *
     * @mbggenerated
     */
    public String getCertificateName() {
        return certificateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchantinfo_copy.certificate_name
     *
     * @param certificateName the value for loan_merchantinfo_copy.certificate_name
     *
     * @mbggenerated
     */
    public void setCertificateName(String certificateName) {
        this.certificateName = certificateName == null ? null : certificateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchantinfo_copy.certificate_url
     *
     * @return the value of loan_merchantinfo_copy.certificate_url
     *
     * @mbggenerated
     */
    public String getCertificateUrl() {
        return certificateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchantinfo_copy.certificate_url
     *
     * @param certificateUrl the value for loan_merchantinfo_copy.certificate_url
     *
     * @mbggenerated
     */
    public void setCertificateUrl(String certificateUrl) {
        this.certificateUrl = certificateUrl == null ? null : certificateUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchantinfo_copy.status
     *
     * @return the value of loan_merchantinfo_copy.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchantinfo_copy.status
     *
     * @param status the value for loan_merchantinfo_copy.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchantinfo_copy.createtime
     *
     * @return the value of loan_merchantinfo_copy.createtime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchantinfo_copy.createtime
     *
     * @param createtime the value for loan_merchantinfo_copy.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchantinfo_copy.updatetime
     *
     * @return the value of loan_merchantinfo_copy.updatetime
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchantinfo_copy.updatetime
     *
     * @param updatetime the value for loan_merchantinfo_copy.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }
}