package com.xiaochong.loan.background.entity.po;

import java.util.Date;

public class MerchDataTemplateProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merch_data_template_project.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merch_data_template_project.data_temp_id
     *
     * @mbggenerated
     */
    private Integer dataTempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merch_data_template_project.project_name
     *
     * @mbggenerated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merch_data_template_project.file_type
     *
     * @mbggenerated
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merch_data_template_project.mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merch_data_template_project.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merch_data_template_project.serial_no
     *
     * @mbggenerated
     */
    private Integer serialNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merch_data_template_project.id
     *
     * @return the value of loan_merch_data_template_project.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merch_data_template_project.id
     *
     * @param id the value for loan_merch_data_template_project.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merch_data_template_project.data_temp_id
     *
     * @return the value of loan_merch_data_template_project.data_temp_id
     *
     * @mbggenerated
     */
    public Integer getDataTempId() {
        return dataTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merch_data_template_project.data_temp_id
     *
     * @param dataTempId the value for loan_merch_data_template_project.data_temp_id
     *
     * @mbggenerated
     */
    public void setDataTempId(Integer dataTempId) {
        this.dataTempId = dataTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merch_data_template_project.project_name
     *
     * @return the value of loan_merch_data_template_project.project_name
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merch_data_template_project.project_name
     *
     * @param projectName the value for loan_merch_data_template_project.project_name
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merch_data_template_project.file_type
     *
     * @return the value of loan_merch_data_template_project.file_type
     *
     * @mbggenerated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merch_data_template_project.file_type
     *
     * @param fileType the value for loan_merch_data_template_project.file_type
     *
     * @mbggenerated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merch_data_template_project.mark
     *
     * @return the value of loan_merch_data_template_project.mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merch_data_template_project.mark
     *
     * @param mark the value for loan_merch_data_template_project.mark
     *
     * @mbggenerated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merch_data_template_project.create_time
     *
     * @return the value of loan_merch_data_template_project.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merch_data_template_project.create_time
     *
     * @param createTime the value for loan_merch_data_template_project.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merch_data_template_project.serial_no
     *
     * @return the value of loan_merch_data_template_project.serial_no
     *
     * @mbggenerated
     */
    public Integer getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merch_data_template_project.serial_no
     *
     * @param serialNo the value for loan_merch_data_template_project.serial_no
     *
     * @mbggenerated
     */
    public void setSerialNo(Integer serialNo) {
        this.serialNo = serialNo;
    }
}