package com.xiaochong.loan.background.entity.po;

import java.util.Date;

public class MerchantSubmitProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchant_submit_project.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchant_submit_project.borrower_id
     *
     * @mbggenerated
     */
    private Integer applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchant_submit_project.project_id
     *
     * @mbggenerated
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchant_submit_project.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchant_submit_project.file_url
     *
     * @mbggenerated
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchant_submit_project.submit_by
     *
     * @mbggenerated
     */
    private Integer submitBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_merchant_submit_project.submit_time
     *
     * @mbggenerated
     */
    private Date submitTime;

    private String content;

    private String inputType;

    public String getInputType() {
        return inputType;
    }

    public void setInputType(String inputType) {
        this.inputType = inputType;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchant_submit_project.id
     *
     * @return the value of loan_merchant_submit_project.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchant_submit_project.id
     *
     * @param id the value for loan_merchant_submit_project.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getApplicationId() {
        return applicationId;
    }

    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchant_submit_project.project_id
     *
     * @return the value of loan_merchant_submit_project.project_id
     *
     * @mbggenerated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchant_submit_project.project_id
     *
     * @param projectId the value for loan_merchant_submit_project.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchant_submit_project.file_name
     *
     * @return the value of loan_merchant_submit_project.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchant_submit_project.file_name
     *
     * @param fileName the value for loan_merchant_submit_project.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchant_submit_project.file_url
     *
     * @return the value of loan_merchant_submit_project.file_url
     *
     * @mbggenerated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchant_submit_project.file_url
     *
     * @param fileUrl the value for loan_merchant_submit_project.file_url
     *
     * @mbggenerated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchant_submit_project.submit_by
     *
     * @return the value of loan_merchant_submit_project.submit_by
     *
     * @mbggenerated
     */
    public Integer getSubmitBy() {
        return submitBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchant_submit_project.submit_by
     *
     * @param submitBy the value for loan_merchant_submit_project.submit_by
     *
     * @mbggenerated
     */
    public void setSubmitBy(Integer submitBy) {
        this.submitBy = submitBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_merchant_submit_project.submit_time
     *
     * @return the value of loan_merchant_submit_project.submit_time
     *
     * @mbggenerated
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_merchant_submit_project.submit_time
     *
     * @param submitTime the value for loan_merchant_submit_project.submit_time
     *
     * @mbggenerated
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }
}