package com.xiaochong.loan.background.entity.po;

import java.util.Date;

public class OrderUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.order_token
     *
     * @mbggenerated
     */
    private String orderToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.merch_id
     *
     * @mbggenerated
     */
    private Integer merchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.phone_password
     *
     * @mbggenerated
     */
    private String phonePassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.education_account
     *
     * @mbggenerated
     */
    private String educationAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.education_password
     *
     * @mbggenerated
     */
    private String educationPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.home_address
     *
     * @mbggenerated
     */
    private String homeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.home_address_province
     *
     * @mbggenerated
     */
    private String homeAddressProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.home_address_city
     *
     * @mbggenerated
     */
    private String homeAddressCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.home_address_area
     *
     * @mbggenerated
     */
    private String homeAddressArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.permanent_address
     *
     * @mbggenerated
     */
    private String permanentAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.client_ip
     *
     * @mbggenerated
     */
    private String clientIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.end_latitude
     *
     * @mbggenerated
     */
    private String endLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.end_longitude
     *
     * @mbggenerated
     */
    private String endLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.auth_start_time
     *
     * @mbggenerated
     */
    private Date authStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_user_info.auth_end_time
     *
     * @mbggenerated
     */
    private Date authEndTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.id
     *
     * @return the value of loan_order_user_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.id
     *
     * @param id the value for loan_order_user_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.order_no
     *
     * @return the value of loan_order_user_info.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.order_no
     *
     * @param orderNo the value for loan_order_user_info.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.order_token
     *
     * @return the value of loan_order_user_info.order_token
     *
     * @mbggenerated
     */
    public String getOrderToken() {
        return orderToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.order_token
     *
     * @param orderToken the value for loan_order_user_info.order_token
     *
     * @mbggenerated
     */
    public void setOrderToken(String orderToken) {
        this.orderToken = orderToken == null ? null : orderToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.merch_id
     *
     * @return the value of loan_order_user_info.merch_id
     *
     * @mbggenerated
     */
    public Integer getMerchId() {
        return merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.merch_id
     *
     * @param merchId the value for loan_order_user_info.merch_id
     *
     * @mbggenerated
     */
    public void setMerchId(Integer merchId) {
        this.merchId = merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.realname
     *
     * @return the value of loan_order_user_info.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.realname
     *
     * @param realname the value for loan_order_user_info.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.id_card
     *
     * @return the value of loan_order_user_info.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.id_card
     *
     * @param idCard the value for loan_order_user_info.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.phone
     *
     * @return the value of loan_order_user_info.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.phone
     *
     * @param phone the value for loan_order_user_info.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.phone_password
     *
     * @return the value of loan_order_user_info.phone_password
     *
     * @mbggenerated
     */
    public String getPhonePassword() {
        return phonePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.phone_password
     *
     * @param phonePassword the value for loan_order_user_info.phone_password
     *
     * @mbggenerated
     */
    public void setPhonePassword(String phonePassword) {
        this.phonePassword = phonePassword == null ? null : phonePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.sex
     *
     * @return the value of loan_order_user_info.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.sex
     *
     * @param sex the value for loan_order_user_info.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.status
     *
     * @return the value of loan_order_user_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.status
     *
     * @param status the value for loan_order_user_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.education_account
     *
     * @return the value of loan_order_user_info.education_account
     *
     * @mbggenerated
     */
    public String getEducationAccount() {
        return educationAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.education_account
     *
     * @param educationAccount the value for loan_order_user_info.education_account
     *
     * @mbggenerated
     */
    public void setEducationAccount(String educationAccount) {
        this.educationAccount = educationAccount == null ? null : educationAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.education_password
     *
     * @return the value of loan_order_user_info.education_password
     *
     * @mbggenerated
     */
    public String getEducationPassword() {
        return educationPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.education_password
     *
     * @param educationPassword the value for loan_order_user_info.education_password
     *
     * @mbggenerated
     */
    public void setEducationPassword(String educationPassword) {
        this.educationPassword = educationPassword == null ? null : educationPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.home_address
     *
     * @return the value of loan_order_user_info.home_address
     *
     * @mbggenerated
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.home_address
     *
     * @param homeAddress the value for loan_order_user_info.home_address
     *
     * @mbggenerated
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress == null ? null : homeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.home_address_province
     *
     * @return the value of loan_order_user_info.home_address_province
     *
     * @mbggenerated
     */
    public String getHomeAddressProvince() {
        return homeAddressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.home_address_province
     *
     * @param homeAddressProvince the value for loan_order_user_info.home_address_province
     *
     * @mbggenerated
     */
    public void setHomeAddressProvince(String homeAddressProvince) {
        this.homeAddressProvince = homeAddressProvince == null ? null : homeAddressProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.home_address_city
     *
     * @return the value of loan_order_user_info.home_address_city
     *
     * @mbggenerated
     */
    public String getHomeAddressCity() {
        return homeAddressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.home_address_city
     *
     * @param homeAddressCity the value for loan_order_user_info.home_address_city
     *
     * @mbggenerated
     */
    public void setHomeAddressCity(String homeAddressCity) {
        this.homeAddressCity = homeAddressCity == null ? null : homeAddressCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.home_address_area
     *
     * @return the value of loan_order_user_info.home_address_area
     *
     * @mbggenerated
     */
    public String getHomeAddressArea() {
        return homeAddressArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.home_address_area
     *
     * @param homeAddressArea the value for loan_order_user_info.home_address_area
     *
     * @mbggenerated
     */
    public void setHomeAddressArea(String homeAddressArea) {
        this.homeAddressArea = homeAddressArea == null ? null : homeAddressArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.permanent_address
     *
     * @return the value of loan_order_user_info.permanent_address
     *
     * @mbggenerated
     */
    public String getPermanentAddress() {
        return permanentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.permanent_address
     *
     * @param permanentAddress the value for loan_order_user_info.permanent_address
     *
     * @mbggenerated
     */
    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress == null ? null : permanentAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.client_ip
     *
     * @return the value of loan_order_user_info.client_ip
     *
     * @mbggenerated
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.client_ip
     *
     * @param clientIp the value for loan_order_user_info.client_ip
     *
     * @mbggenerated
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.latitude
     *
     * @return the value of loan_order_user_info.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.latitude
     *
     * @param latitude the value for loan_order_user_info.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.longitude
     *
     * @return the value of loan_order_user_info.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.longitude
     *
     * @param longitude the value for loan_order_user_info.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.createtime
     *
     * @return the value of loan_order_user_info.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.createtime
     *
     * @param createtime the value for loan_order_user_info.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.updatetime
     *
     * @return the value of loan_order_user_info.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.updatetime
     *
     * @param updatetime the value for loan_order_user_info.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.end_latitude
     *
     * @return the value of loan_order_user_info.end_latitude
     *
     * @mbggenerated
     */
    public String getEndLatitude() {
        return endLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.end_latitude
     *
     * @param endLatitude the value for loan_order_user_info.end_latitude
     *
     * @mbggenerated
     */
    public void setEndLatitude(String endLatitude) {
        this.endLatitude = endLatitude == null ? null : endLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.end_longitude
     *
     * @return the value of loan_order_user_info.end_longitude
     *
     * @mbggenerated
     */
    public String getEndLongitude() {
        return endLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.end_longitude
     *
     * @param endLongitude the value for loan_order_user_info.end_longitude
     *
     * @mbggenerated
     */
    public void setEndLongitude(String endLongitude) {
        this.endLongitude = endLongitude == null ? null : endLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.auth_start_time
     *
     * @return the value of loan_order_user_info.auth_start_time
     *
     * @mbggenerated
     */
    public Date getAuthStartTime() {
        return authStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.auth_start_time
     *
     * @param authStartTime the value for loan_order_user_info.auth_start_time
     *
     * @mbggenerated
     */
    public void setAuthStartTime(Date authStartTime) {
        this.authStartTime = authStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_user_info.auth_end_time
     *
     * @return the value of loan_order_user_info.auth_end_time
     *
     * @mbggenerated
     */
    public Date getAuthEndTime() {
        return authEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_user_info.auth_end_time
     *
     * @param authEndTime the value for loan_order_user_info.auth_end_time
     *
     * @mbggenerated
     */
    public void setAuthEndTime(Date authEndTime) {
        this.authEndTime = authEndTime;
    }
}