package com.xiaochong.loan.background.entity.po;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.proxy_user
     *
     * @mbggenerated
     */
    private Integer proxyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.mer_id
     *
     * @mbggenerated
     */
    private Integer merId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.risk_status
     *
     * @mbggenerated
     */
    private String riskStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.check_status
     *
     * @mbggenerated
     */
    private String checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.checktime
     *
     * @mbggenerated
     */
    private Date checktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.risk_check_result
     *
     * @mbggenerated
     */
    private String riskCheckResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.report_url
     *
     * @mbggenerated
     */
    private String reportUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order.is_old
     *
     * @mbggenerated
     */
    private String isOld;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.id
     *
     * @return the value of loan_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.id
     *
     * @param id the value for loan_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.realname
     *
     * @return the value of loan_order.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.realname
     *
     * @param realname the value for loan_order.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.id_card
     *
     * @return the value of loan_order.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.id_card
     *
     * @param idCard the value for loan_order.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.phone
     *
     * @return the value of loan_order.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.phone
     *
     * @param phone the value for loan_order.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.status
     *
     * @return the value of loan_order.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.status
     *
     * @param status the value for loan_order.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.order_no
     *
     * @return the value of loan_order.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.order_no
     *
     * @param orderNo the value for loan_order.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.token
     *
     * @return the value of loan_order.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.token
     *
     * @param token the value for loan_order.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.createtime
     *
     * @return the value of loan_order.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.createtime
     *
     * @param createtime the value for loan_order.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.updatetime
     *
     * @return the value of loan_order.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.updatetime
     *
     * @param updatetime the value for loan_order.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.user_id
     *
     * @return the value of loan_order.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.user_id
     *
     * @param userId the value for loan_order.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.proxy_user
     *
     * @return the value of loan_order.proxy_user
     *
     * @mbggenerated
     */
    public Integer getProxyUser() {
        return proxyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.proxy_user
     *
     * @param proxyUser the value for loan_order.proxy_user
     *
     * @mbggenerated
     */
    public void setProxyUser(Integer proxyUser) {
        this.proxyUser = proxyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.mer_id
     *
     * @return the value of loan_order.mer_id
     *
     * @mbggenerated
     */
    public Integer getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.mer_id
     *
     * @param merId the value for loan_order.mer_id
     *
     * @mbggenerated
     */
    public void setMerId(Integer merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.risk_status
     *
     * @return the value of loan_order.risk_status
     *
     * @mbggenerated
     */
    public String getRiskStatus() {
        return riskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.risk_status
     *
     * @param riskStatus the value for loan_order.risk_status
     *
     * @mbggenerated
     */
    public void setRiskStatus(String riskStatus) {
        this.riskStatus = riskStatus == null ? null : riskStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.check_status
     *
     * @return the value of loan_order.check_status
     *
     * @mbggenerated
     */
    public String getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.check_status
     *
     * @param checkStatus the value for loan_order.check_status
     *
     * @mbggenerated
     */
    public void setCheckStatus(String checkStatus) {
        this.checkStatus = checkStatus == null ? null : checkStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.checktime
     *
     * @return the value of loan_order.checktime
     *
     * @mbggenerated
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.checktime
     *
     * @param checktime the value for loan_order.checktime
     *
     * @mbggenerated
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.risk_check_result
     *
     * @return the value of loan_order.risk_check_result
     *
     * @mbggenerated
     */
    public String getRiskCheckResult() {
        return riskCheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.risk_check_result
     *
     * @param riskCheckResult the value for loan_order.risk_check_result
     *
     * @mbggenerated
     */
    public void setRiskCheckResult(String riskCheckResult) {
        this.riskCheckResult = riskCheckResult == null ? null : riskCheckResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.report_url
     *
     * @return the value of loan_order.report_url
     *
     * @mbggenerated
     */
    public String getReportUrl() {
        return reportUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.report_url
     *
     * @param reportUrl the value for loan_order.report_url
     *
     * @mbggenerated
     */
    public void setReportUrl(String reportUrl) {
        this.reportUrl = reportUrl == null ? null : reportUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order.is_old
     *
     * @return the value of loan_order.is_old
     *
     * @mbggenerated
     */
    public String getIsOld() {
        return isOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order.is_old
     *
     * @param isOld the value for loan_order.is_old
     *
     * @mbggenerated
     */
    public void setIsOld(String isOld) {
        this.isOld = isOld == null ? null : isOld.trim();
    }
}