package com.xiaochong.loan.background.entity.po;

import java.util.Date;

public class OrderFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_flow.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_flow.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_flow.order_token
     *
     * @mbggenerated
     */
    private String orderToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_flow.merch_id
     *
     * @mbggenerated
     */
    private Integer merchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_flow.flow_no
     *
     * @mbggenerated
     */
    private String flowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_flow.flow_step
     *
     * @mbggenerated
     */
    private Integer flowStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_flow.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_flow.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_order_flow.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_flow.id
     *
     * @return the value of loan_order_flow.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_flow.id
     *
     * @param id the value for loan_order_flow.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_flow.order_no
     *
     * @return the value of loan_order_flow.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_flow.order_no
     *
     * @param orderNo the value for loan_order_flow.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_flow.order_token
     *
     * @return the value of loan_order_flow.order_token
     *
     * @mbggenerated
     */
    public String getOrderToken() {
        return orderToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_flow.order_token
     *
     * @param orderToken the value for loan_order_flow.order_token
     *
     * @mbggenerated
     */
    public void setOrderToken(String orderToken) {
        this.orderToken = orderToken == null ? null : orderToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_flow.merch_id
     *
     * @return the value of loan_order_flow.merch_id
     *
     * @mbggenerated
     */
    public Integer getMerchId() {
        return merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_flow.merch_id
     *
     * @param merchId the value for loan_order_flow.merch_id
     *
     * @mbggenerated
     */
    public void setMerchId(Integer merchId) {
        this.merchId = merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_flow.flow_no
     *
     * @return the value of loan_order_flow.flow_no
     *
     * @mbggenerated
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_flow.flow_no
     *
     * @param flowNo the value for loan_order_flow.flow_no
     *
     * @mbggenerated
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo == null ? null : flowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_flow.flow_step
     *
     * @return the value of loan_order_flow.flow_step
     *
     * @mbggenerated
     */
    public Integer getFlowStep() {
        return flowStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_flow.flow_step
     *
     * @param flowStep the value for loan_order_flow.flow_step
     *
     * @mbggenerated
     */
    public void setFlowStep(Integer flowStep) {
        this.flowStep = flowStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_flow.status
     *
     * @return the value of loan_order_flow.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_flow.status
     *
     * @param status the value for loan_order_flow.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_flow.createtime
     *
     * @return the value of loan_order_flow.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_flow.createtime
     *
     * @param createtime the value for loan_order_flow.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_order_flow.updatetime
     *
     * @return the value of loan_order_flow.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_order_flow.updatetime
     *
     * @param updatetime the value for loan_order_flow.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }


    @Override
    public String toString() {
        return "OrderFlow{" +
                "id=" + id +
                ", orderNo='" + orderNo + '\'' +
                ", orderToken='" + orderToken + '\'' +
                ", merchId=" + merchId +
                ", flowNo='" + flowNo + '\'' +
                ", flowStep=" + flowStep +
                ", status='" + status + '\'' +
                ", createtime=" + createtime +
                ", updatetime=" + updatetime +
                '}';
    }
}