package com.xiaochong.loan.background.entity.po;

public class ProxyuserCopy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_proxyuser_copy.toid
     *
     * @mbggenerated
     */
    private String toid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_proxyuser_copy.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_proxyuser_copy.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_proxyuser_copy.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_proxyuser_copy.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_proxyuser_copy.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_proxyuser_copy.createtime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_proxyuser_copy.merid
     *
     * @mbggenerated
     */
    private String merid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_proxyuser_copy.ismaster
     *
     * @mbggenerated
     */
    private String ismaster;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_proxyuser_copy.toid
     *
     * @return the value of loan_proxyuser_copy.toid
     *
     * @mbggenerated
     */
    public String getToid() {
        return toid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_proxyuser_copy.toid
     *
     * @param toid the value for loan_proxyuser_copy.toid
     *
     * @mbggenerated
     */
    public void setToid(String toid) {
        this.toid = toid == null ? null : toid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_proxyuser_copy.username
     *
     * @return the value of loan_proxyuser_copy.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_proxyuser_copy.username
     *
     * @param username the value for loan_proxyuser_copy.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_proxyuser_copy.pwd
     *
     * @return the value of loan_proxyuser_copy.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_proxyuser_copy.pwd
     *
     * @param pwd the value for loan_proxyuser_copy.pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_proxyuser_copy.email
     *
     * @return the value of loan_proxyuser_copy.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_proxyuser_copy.email
     *
     * @param email the value for loan_proxyuser_copy.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_proxyuser_copy.phone
     *
     * @return the value of loan_proxyuser_copy.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_proxyuser_copy.phone
     *
     * @param phone the value for loan_proxyuser_copy.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_proxyuser_copy.status
     *
     * @return the value of loan_proxyuser_copy.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_proxyuser_copy.status
     *
     * @param status the value for loan_proxyuser_copy.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_proxyuser_copy.createtime
     *
     * @return the value of loan_proxyuser_copy.createtime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_proxyuser_copy.createtime
     *
     * @param createtime the value for loan_proxyuser_copy.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_proxyuser_copy.merid
     *
     * @return the value of loan_proxyuser_copy.merid
     *
     * @mbggenerated
     */
    public String getMerid() {
        return merid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_proxyuser_copy.merid
     *
     * @param merid the value for loan_proxyuser_copy.merid
     *
     * @mbggenerated
     */
    public void setMerid(String merid) {
        this.merid = merid == null ? null : merid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_proxyuser_copy.ismaster
     *
     * @return the value of loan_proxyuser_copy.ismaster
     *
     * @mbggenerated
     */
    public String getIsmaster() {
        return ismaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_proxyuser_copy.ismaster
     *
     * @param ismaster the value for loan_proxyuser_copy.ismaster
     *
     * @mbggenerated
     */
    public void setIsmaster(String ismaster) {
        this.ismaster = ismaster == null ? null : ismaster.trim();
    }
}