package com.xiaochong.loan.background.entity.po;

import java.math.BigDecimal;
import java.util.Date;

public class RateTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.rate_name
     *
     * @mbggenerated
     */
    private String rateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.staging_type
     *
     * @mbggenerated
     */
    private Integer stagingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.interest_rate
     *
     * @mbggenerated
     */
    private BigDecimal interestRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.service_charge
     *
     * @mbggenerated
     */
    private BigDecimal serviceCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.deposit_type
     *
     * @mbggenerated
     */
    private Integer depositType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.deposit_money
     *
     * @mbggenerated
     */
    private BigDecimal depositMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.overdue_type
     *
     * @mbggenerated
     */
    private Integer overdueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.overdue_money_type
     *
     * @mbggenerated
     */
    private Integer overdueMoneyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.overdue_rate
     *
     * @mbggenerated
     */
    private BigDecimal overdueRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.overdue_constant
     *
     * @mbggenerated
     */
    private BigDecimal overdueConstant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.mer_id
     *
     * @mbggenerated
     */
    private Integer merId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_rate_template.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.id
     *
     * @return the value of loan_rate_template.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.id
     *
     * @param id the value for loan_rate_template.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.rate_name
     *
     * @return the value of loan_rate_template.rate_name
     *
     * @mbggenerated
     */
    public String getRateName() {
        return rateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.rate_name
     *
     * @param rateName the value for loan_rate_template.rate_name
     *
     * @mbggenerated
     */
    public void setRateName(String rateName) {
        this.rateName = rateName == null ? null : rateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.staging_type
     *
     * @return the value of loan_rate_template.staging_type
     *
     * @mbggenerated
     */
    public Integer getStagingType() {
        return stagingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.staging_type
     *
     * @param stagingType the value for loan_rate_template.staging_type
     *
     * @mbggenerated
     */
    public void setStagingType(Integer stagingType) {
        this.stagingType = stagingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.interest_rate
     *
     * @return the value of loan_rate_template.interest_rate
     *
     * @mbggenerated
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.interest_rate
     *
     * @param interestRate the value for loan_rate_template.interest_rate
     *
     * @mbggenerated
     */
    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.service_charge
     *
     * @return the value of loan_rate_template.service_charge
     *
     * @mbggenerated
     */
    public BigDecimal getServiceCharge() {
        return serviceCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.service_charge
     *
     * @param serviceCharge the value for loan_rate_template.service_charge
     *
     * @mbggenerated
     */
    public void setServiceCharge(BigDecimal serviceCharge) {
        this.serviceCharge = serviceCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.deposit_type
     *
     * @return the value of loan_rate_template.deposit_type
     *
     * @mbggenerated
     */
    public Integer getDepositType() {
        return depositType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.deposit_type
     *
     * @param depositType the value for loan_rate_template.deposit_type
     *
     * @mbggenerated
     */
    public void setDepositType(Integer depositType) {
        this.depositType = depositType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.deposit_money
     *
     * @return the value of loan_rate_template.deposit_money
     *
     * @mbggenerated
     */
    public BigDecimal getDepositMoney() {
        return depositMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.deposit_money
     *
     * @param depositMoney the value for loan_rate_template.deposit_money
     *
     * @mbggenerated
     */
    public void setDepositMoney(BigDecimal depositMoney) {
        this.depositMoney = depositMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.overdue_type
     *
     * @return the value of loan_rate_template.overdue_type
     *
     * @mbggenerated
     */
    public Integer getOverdueType() {
        return overdueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.overdue_type
     *
     * @param overdueType the value for loan_rate_template.overdue_type
     *
     * @mbggenerated
     */
    public void setOverdueType(Integer overdueType) {
        this.overdueType = overdueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.overdue_money_type
     *
     * @return the value of loan_rate_template.overdue_money_type
     *
     * @mbggenerated
     */
    public Integer getOverdueMoneyType() {
        return overdueMoneyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.overdue_money_type
     *
     * @param overdueMoneyType the value for loan_rate_template.overdue_money_type
     *
     * @mbggenerated
     */
    public void setOverdueMoneyType(Integer overdueMoneyType) {
        this.overdueMoneyType = overdueMoneyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.overdue_rate
     *
     * @return the value of loan_rate_template.overdue_rate
     *
     * @mbggenerated
     */
    public BigDecimal getOverdueRate() {
        return overdueRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.overdue_rate
     *
     * @param overdueRate the value for loan_rate_template.overdue_rate
     *
     * @mbggenerated
     */
    public void setOverdueRate(BigDecimal overdueRate) {
        this.overdueRate = overdueRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.overdue_constant
     *
     * @return the value of loan_rate_template.overdue_constant
     *
     * @mbggenerated
     */
    public BigDecimal getOverdueConstant() {
        return overdueConstant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.overdue_constant
     *
     * @param overdueConstant the value for loan_rate_template.overdue_constant
     *
     * @mbggenerated
     */
    public void setOverdueConstant(BigDecimal overdueConstant) {
        this.overdueConstant = overdueConstant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.mer_id
     *
     * @return the value of loan_rate_template.mer_id
     *
     * @mbggenerated
     */
    public Integer getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.mer_id
     *
     * @param merId the value for loan_rate_template.mer_id
     *
     * @mbggenerated
     */
    public void setMerId(Integer merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.create_user
     *
     * @return the value of loan_rate_template.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.create_user
     *
     * @param createUser the value for loan_rate_template.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.update_user
     *
     * @return the value of loan_rate_template.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.update_user
     *
     * @param updateUser the value for loan_rate_template.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.create_time
     *
     * @return the value of loan_rate_template.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.create_time
     *
     * @param createTime the value for loan_rate_template.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_rate_template.update_time
     *
     * @return the value of loan_rate_template.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_rate_template.update_time
     *
     * @param updateTime the value for loan_rate_template.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}