package com.xiaochong.loan.background.entity.po;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class RepaymentPlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.id
     *
     * @mbggenerated
     */
    private Integer id;

    private Integer merchId;

    private Integer borrowerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.application_id
     *
     * @mbggenerated
     */
    private Integer applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.stage_no
     *
     * @mbggenerated
     */
    private Integer stageNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.return_time
     *
     * @mbggenerated
     */
    private Date returnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.principal_money
     *
     * @mbggenerated
     */
    private BigDecimal principalMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.interest
     *
     * @mbggenerated
     */
    private BigDecimal interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.punish_interest
     *
     * @mbggenerated
     */
    private BigDecimal punishInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.whole_money
     *
     * @mbggenerated
     */
    private BigDecimal wholeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.practical_time
     *
     * @mbggenerated
     */
    private Date practicalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.update_by
     *
     * @mbggenerated
     */
    private Integer updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    private Integer overdueDays;

    private BigDecimal reductiveMoney;

    private List<Integer> applicationIds;

    private Integer repaymentUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_plan.repayment_time
     *
     * @mbggenerated
     */
    private Date repaymentTime;

    public Integer getRepaymentUser() {
        return repaymentUser;
    }

    public void setRepaymentUser(Integer repaymentUser) {
        this.repaymentUser = repaymentUser;
    }

    public Date getRepaymentTime() {
        return repaymentTime;
    }

    public void setRepaymentTime(Date repaymentTime) {
        this.repaymentTime = repaymentTime;
    }

    public Integer getBorrowerId() {
        return borrowerId;
    }

    public void setBorrowerId(Integer borrowerId) {
        this.borrowerId = borrowerId;
    }

    public List<Integer> getApplicationIds() {
        return applicationIds;
    }

    public void setApplicationIds(List<Integer> applicationIds) {
        this.applicationIds = applicationIds;
    }

    public Integer getOverdueDays() {
        return overdueDays;
    }

    public void setOverdueDays(Integer overdueDays) {
        this.overdueDays = overdueDays;
    }

    public BigDecimal getReductiveMoney() {
        return reductiveMoney;
    }

    public void setReductiveMoney(BigDecimal reductiveMoney) {
        this.reductiveMoney = reductiveMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_plan.id
     *
     * @return the value of loan_repayment_plan.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_plan.id
     *
     * @param id the value for loan_repayment_plan.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_plan.application_id
     *
     * @return the value of loan_repayment_plan.application_id
     *
     * @mbggenerated
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_plan.application_id
     *
     * @param applicationId the value for loan_repayment_plan.application_id
     *
     * @mbggenerated
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_plan.stage_no
     *
     * @return the value of loan_repayment_plan.stage_no
     *
     * @mbggenerated
     */
    public Integer getStageNo() {
        return stageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_plan.stage_no
     *
     * @param stageNo the value for loan_repayment_plan.stage_no
     *
     * @mbggenerated
     */
    public void setStageNo(Integer stageNo) {
        this.stageNo = stageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_plan.return_time
     *
     * @return the value of loan_repayment_plan.return_time
     *
     * @mbggenerated
     */
    public Date getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_plan.return_time
     *
     * @param returnTime the value for loan_repayment_plan.return_time
     *
     * @mbggenerated
     */
    public void setReturnTime(Date returnTime) {
        this.returnTime = returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_plan.principal_money
     *
     * @return the value of loan_repayment_plan.principal_money
     *
     * @mbggenerated
     */
    public BigDecimal getPrincipalMoney() {
        return principalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_plan.principal_money
     *
     * @param principalMoney the value for loan_repayment_plan.principal_money
     *
     * @mbggenerated
     */
    public void setPrincipalMoney(BigDecimal principalMoney) {
        this.principalMoney = principalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_plan.interest
     *
     * @return the value of loan_repayment_plan.interest
     *
     * @mbggenerated
     */
    public BigDecimal getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_plan.interest
     *
     * @param interest the value for loan_repayment_plan.interest
     *
     * @mbggenerated
     */
    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_plan.punish_interest
     *
     * @return the value of loan_repayment_plan.punish_interest
     *
     * @mbggenerated
     */
    public BigDecimal getPunishInterest() {
        return punishInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_plan.punish_interest
     *
     * @param punishInterest the value for loan_repayment_plan.punish_interest
     *
     * @mbggenerated
     */
    public void setPunishInterest(BigDecimal punishInterest) {
        this.punishInterest = punishInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_plan.whole_money
     *
     * @return the value of loan_repayment_plan.whole_money
     *
     * @mbggenerated
     */
    public BigDecimal getWholeMoney() {
        return wholeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_plan.whole_money
     *
     * @param wholeMoney the value for loan_repayment_plan.whole_money
     *
     * @mbggenerated
     */
    public void setWholeMoney(BigDecimal wholeMoney) {
        this.wholeMoney = wholeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_plan.status
     *
     * @return the value of loan_repayment_plan.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_plan.status
     *
     * @param status the value for loan_repayment_plan.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_plan.practical_time
     *
     * @return the value of loan_repayment_plan.practical_time
     *
     * @mbggenerated
     */
    public Date getPracticalTime() {
        return practicalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_plan.practical_time
     *
     * @param practicalTime the value for loan_repayment_plan.practical_time
     *
     * @mbggenerated
     */
    public void setPracticalTime(Date practicalTime) {
        this.practicalTime = practicalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_plan.create_by
     *
     * @return the value of loan_repayment_plan.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_plan.create_by
     *
     * @param createBy the value for loan_repayment_plan.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_plan.create_time
     *
     * @return the value of loan_repayment_plan.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_plan.create_time
     *
     * @param createTime the value for loan_repayment_plan.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_plan.update_by
     *
     * @return the value of loan_repayment_plan.update_by
     *
     * @mbggenerated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_plan.update_by
     *
     * @param updateBy the value for loan_repayment_plan.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_plan.update_time
     *
     * @return the value of loan_repayment_plan.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_plan.update_time
     *
     * @param updateTime the value for loan_repayment_plan.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getMerchId() {
        return merchId;
    }

    public void setMerchId(Integer merchId) {
        this.merchId = merchId;
    }

    @Override
    public String toString() {
        return "RepaymentPlan{" +
                "id=" + id +
                ", merchId=" + merchId +
                ", borrowerId=" + borrowerId +
                ", applicationId=" + applicationId +
                ", stageNo=" + stageNo +
                ", returnTime=" + returnTime +
                ", principalMoney=" + principalMoney +
                ", interest=" + interest +
                ", punishInterest=" + punishInterest +
                ", wholeMoney=" + wholeMoney +
                ", status='" + status + '\'' +
                ", practicalTime=" + practicalTime +
                ", createBy=" + createBy +
                ", createTime=" + createTime +
                ", updateBy=" + updateBy +
                ", updateTime=" + updateTime +
                ", overdueDays=" + overdueDays +
                ", reductiveMoney=" + reductiveMoney +
                ", applicationIds=" + applicationIds +
                ", repaymentUser=" + repaymentUser +
                ", repaymentTime=" + repaymentTime +
                '}';
    }
}