package com.xiaochong.loan.background.entity.po;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class RepaymentSerialRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_serial_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_serial_record.merch_id
     *
     * @mbggenerated
     */
    private Integer merchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_serial_record.borrower_id
     *
     * @mbggenerated
     */
    private Integer borrowerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_serial_record.deal_serial_no
     *
     * @mbggenerated
     */
    private String dealSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_serial_record.accounting_serial_no
     *
     * @mbggenerated
     */
    private String accountingSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_serial_record.deal_time
     *
     * @mbggenerated
     */
    private Date dealTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_serial_record.transfer_account_name
     *
     * @mbggenerated
     */
    private String transferAccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_serial_record.transfer_money
     *
     * @mbggenerated
     */
    private BigDecimal transferMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_serial_record.transfer_mark
     *
     * @mbggenerated
     */
    private String transferMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_serial_record.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_serial_record.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_serial_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_serial_record.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_repayment_serial_record.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;


    private String source;

    private String updateSource;

    private List<Integer> borrowerIds;

    private String lastMatchType;

    public String getLastMatchType() {
        return lastMatchType;
    }

    public void setLastMatchType(String lastMatchType) {
        this.lastMatchType = lastMatchType;
    }

    public List<Integer> getBorrowerIds() {
        return borrowerIds;
    }

    public void setBorrowerIds(List<Integer> borrowerIds) {
        this.borrowerIds = borrowerIds;
    }

    public String getUpdateSource() {
        return updateSource;
    }

    public void setUpdateSource(String updateSource) {
        this.updateSource = updateSource;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getAccountingSerialNo() {
        return accountingSerialNo;
    }

    public void setAccountingSerialNo(String accountingSerialNo) {
        this.accountingSerialNo = accountingSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_serial_record.id
     *
     * @return the value of loan_repayment_serial_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_serial_record.id
     *
     * @param id the value for loan_repayment_serial_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_serial_record.merch_id
     *
     * @return the value of loan_repayment_serial_record.merch_id
     *
     * @mbggenerated
     */
    public Integer getMerchId() {
        return merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_serial_record.merch_id
     *
     * @param merchId the value for loan_repayment_serial_record.merch_id
     *
     * @mbggenerated
     */
    public void setMerchId(Integer merchId) {
        this.merchId = merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_serial_record.borrower_id
     *
     * @return the value of loan_repayment_serial_record.borrower_id
     *
     * @mbggenerated
     */
    public Integer getBorrowerId() {
        return borrowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_serial_record.borrower_id
     *
     * @param borrowerId the value for loan_repayment_serial_record.borrower_id
     *
     * @mbggenerated
     */
    public void setBorrowerId(Integer borrowerId) {
        this.borrowerId = borrowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_serial_record.deal_serial_no
     *
     * @return the value of loan_repayment_serial_record.deal_serial_no
     *
     * @mbggenerated
     */
    public String getDealSerialNo() {
        return dealSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_serial_record.deal_serial_no
     *
     * @param dealSerialNo the value for loan_repayment_serial_record.deal_serial_no
     *
     * @mbggenerated
     */
    public void setDealSerialNo(String dealSerialNo) {
        this.dealSerialNo = dealSerialNo == null ? null : dealSerialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_serial_record.deal_time
     *
     * @return the value of loan_repayment_serial_record.deal_time
     *
     * @mbggenerated
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_serial_record.deal_time
     *
     * @param dealTime the value for loan_repayment_serial_record.deal_time
     *
     * @mbggenerated
     */
    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_serial_record.transfer_account_name
     *
     * @return the value of loan_repayment_serial_record.transfer_account_name
     *
     * @mbggenerated
     */
    public String getTransferAccountName() {
        return transferAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_serial_record.transfer_account_name
     *
     * @param transferAccountName the value for loan_repayment_serial_record.transfer_account_name
     *
     * @mbggenerated
     */
    public void setTransferAccountName(String transferAccountName) {
        this.transferAccountName = transferAccountName == null ? null : transferAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_serial_record.transfer_money
     *
     * @return the value of loan_repayment_serial_record.transfer_money
     *
     * @mbggenerated
     */
    public BigDecimal getTransferMoney() {
        return transferMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_serial_record.transfer_money
     *
     * @param transferMoney the value for loan_repayment_serial_record.transfer_money
     *
     * @mbggenerated
     */
    public void setTransferMoney(BigDecimal transferMoney) {
        this.transferMoney = transferMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_serial_record.transfer_mark
     *
     * @return the value of loan_repayment_serial_record.transfer_mark
     *
     * @mbggenerated
     */
    public String getTransferMark() {
        return transferMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_serial_record.transfer_mark
     *
     * @param transferMark the value for loan_repayment_serial_record.transfer_mark
     *
     * @mbggenerated
     */
    public void setTransferMark(String transferMark) {
        this.transferMark = transferMark == null ? null : transferMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_serial_record.status
     *
     * @return the value of loan_repayment_serial_record.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_serial_record.status
     *
     * @param status the value for loan_repayment_serial_record.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_serial_record.create_user
     *
     * @return the value of loan_repayment_serial_record.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_serial_record.create_user
     *
     * @param createUser the value for loan_repayment_serial_record.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_serial_record.create_time
     *
     * @return the value of loan_repayment_serial_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_serial_record.create_time
     *
     * @param createTime the value for loan_repayment_serial_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_serial_record.update_user
     *
     * @return the value of loan_repayment_serial_record.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_serial_record.update_user
     *
     * @param updateUser the value for loan_repayment_serial_record.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_repayment_serial_record.update_time
     *
     * @return the value of loan_repayment_serial_record.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_repayment_serial_record.update_time
     *
     * @param updateTime the value for loan_repayment_serial_record.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "RepaymentSerialRecord{" +
                "id=" + id +
                ", merchId=" + merchId +
                ", borrowerId=" + borrowerId +
                ", dealSerialNo='" + dealSerialNo + '\'' +
                ", accountingSerialNo='" + accountingSerialNo + '\'' +
                ", dealTime=" + dealTime +
                ", transferAccountName='" + transferAccountName + '\'' +
                ", transferMoney=" + transferMoney +
                ", transferMark='" + transferMark + '\'' +
                ", status='" + status + '\'' +
                ", createUser=" + createUser +
                ", createTime=" + createTime +
                ", updateUser=" + updateUser +
                ", updateTime=" + updateTime +
                '}';
    }
}