package com.xiaochong.loan.background.entity.po;

public class ReportZhimaExtend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_extend.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_extend.key
     *
     * @mbggenerated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_extend.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_extend.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_extend.zhima_id
     *
     * @mbggenerated
     */
    private Integer zhimaId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_extend.id
     *
     * @return the value of loan_report_zhima_extend.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_extend.id
     *
     * @param id the value for loan_report_zhima_extend.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_extend.key
     *
     * @return the value of loan_report_zhima_extend.key
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_extend.key
     *
     * @param key the value for loan_report_zhima_extend.key
     *
     * @mbggenerated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_extend.value
     *
     * @return the value of loan_report_zhima_extend.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_extend.value
     *
     * @param value the value for loan_report_zhima_extend.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_extend.description
     *
     * @return the value of loan_report_zhima_extend.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_extend.description
     *
     * @param description the value for loan_report_zhima_extend.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_extend.zhima_id
     *
     * @return the value of loan_report_zhima_extend.zhima_id
     *
     * @mbggenerated
     */
    public Integer getZhimaId() {
        return zhimaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_extend.zhima_id
     *
     * @param zhimaId the value for loan_report_zhima_extend.zhima_id
     *
     * @mbggenerated
     */
    public void setZhimaId(Integer zhimaId) {
        this.zhimaId = zhimaId;
    }
}