package com.xiaochong.loan.background.entity.po;

import java.util.Date;

public class ReportZhimaInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_info.biz_code
     *
     * @mbggenerated
     */
    private String bizCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_info.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_info.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_info.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_info.refresh_time
     *
     * @mbggenerated
     */
    private String refreshTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_info.settlement
     *
     * @mbggenerated
     */
    private String settlement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_info.statement
     *
     * @mbggenerated
     */
    private String statement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_info.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_zhima_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_info.id
     *
     * @return the value of loan_report_zhima_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_info.id
     *
     * @param id the value for loan_report_zhima_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_info.biz_code
     *
     * @return the value of loan_report_zhima_info.biz_code
     *
     * @mbggenerated
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_info.biz_code
     *
     * @param bizCode the value for loan_report_zhima_info.biz_code
     *
     * @mbggenerated
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_info.level
     *
     * @return the value of loan_report_zhima_info.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_info.level
     *
     * @param level the value for loan_report_zhima_info.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_info.type
     *
     * @return the value of loan_report_zhima_info.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_info.type
     *
     * @param type the value for loan_report_zhima_info.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_info.code
     *
     * @return the value of loan_report_zhima_info.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_info.code
     *
     * @param code the value for loan_report_zhima_info.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_info.refresh_time
     *
     * @return the value of loan_report_zhima_info.refresh_time
     *
     * @mbggenerated
     */
    public String getRefreshTime() {
        return refreshTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_info.refresh_time
     *
     * @param refreshTime the value for loan_report_zhima_info.refresh_time
     *
     * @mbggenerated
     */
    public void setRefreshTime(String refreshTime) {
        this.refreshTime = refreshTime == null ? null : refreshTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_info.settlement
     *
     * @return the value of loan_report_zhima_info.settlement
     *
     * @mbggenerated
     */
    public String getSettlement() {
        return settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_info.settlement
     *
     * @param settlement the value for loan_report_zhima_info.settlement
     *
     * @mbggenerated
     */
    public void setSettlement(String settlement) {
        this.settlement = settlement == null ? null : settlement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_info.status
     *
     * @return the value of loan_report_zhima_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_info.status
     *
     * @param status the value for loan_report_zhima_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_info.statement
     *
     * @return the value of loan_report_zhima_info.statement
     *
     * @mbggenerated
     */
    public String getStatement() {
        return statement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_info.statement
     *
     * @param statement the value for loan_report_zhima_info.statement
     *
     * @mbggenerated
     */
    public void setStatement(String statement) {
        this.statement = statement == null ? null : statement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_info.order_no
     *
     * @return the value of loan_report_zhima_info.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_info.order_no
     *
     * @param orderNo the value for loan_report_zhima_info.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_zhima_info.create_time
     *
     * @return the value of loan_report_zhima_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_zhima_info.create_time
     *
     * @param createTime the value for loan_report_zhima_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}