package com.xiaochong.loan.background.entity.po;

import java.util.Date;

public class ReportCallRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_call_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_call_record.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_call_record.tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_call_record.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_call_record.dialing_count
     *
     * @mbggenerated
     */
    private String dialingCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_call_record.called_count
     *
     * @mbggenerated
     */
    private String calledCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_call_record.frequency
     *
     * @mbggenerated
     */
    private String frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_call_record.duration
     *
     * @mbggenerated
     */
    private String duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_call_record.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_report_call_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_call_record.id
     *
     * @return the value of loan_report_call_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_call_record.id
     *
     * @param id the value for loan_report_call_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_call_record.phone
     *
     * @return the value of loan_report_call_record.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_call_record.phone
     *
     * @param phone the value for loan_report_call_record.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_call_record.tag
     *
     * @return the value of loan_report_call_record.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_call_record.tag
     *
     * @param tag the value for loan_report_call_record.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_call_record.location
     *
     * @return the value of loan_report_call_record.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_call_record.location
     *
     * @param location the value for loan_report_call_record.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_call_record.dialing_count
     *
     * @return the value of loan_report_call_record.dialing_count
     *
     * @mbggenerated
     */
    public String getDialingCount() {
        return dialingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_call_record.dialing_count
     *
     * @param dialingCount the value for loan_report_call_record.dialing_count
     *
     * @mbggenerated
     */
    public void setDialingCount(String dialingCount) {
        this.dialingCount = dialingCount == null ? null : dialingCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_call_record.called_count
     *
     * @return the value of loan_report_call_record.called_count
     *
     * @mbggenerated
     */
    public String getCalledCount() {
        return calledCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_call_record.called_count
     *
     * @param calledCount the value for loan_report_call_record.called_count
     *
     * @mbggenerated
     */
    public void setCalledCount(String calledCount) {
        this.calledCount = calledCount == null ? null : calledCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_call_record.frequency
     *
     * @return the value of loan_report_call_record.frequency
     *
     * @mbggenerated
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_call_record.frequency
     *
     * @param frequency the value for loan_report_call_record.frequency
     *
     * @mbggenerated
     */
    public void setFrequency(String frequency) {
        this.frequency = frequency == null ? null : frequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_call_record.duration
     *
     * @return the value of loan_report_call_record.duration
     *
     * @mbggenerated
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_call_record.duration
     *
     * @param duration the value for loan_report_call_record.duration
     *
     * @mbggenerated
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_call_record.order_no
     *
     * @return the value of loan_report_call_record.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_call_record.order_no
     *
     * @param orderNo the value for loan_report_call_record.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_report_call_record.create_time
     *
     * @return the value of loan_report_call_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_report_call_record.create_time
     *
     * @param createTime the value for loan_report_call_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}