package com.xiaochong.loan.background.entity.po;

public class ResourceMeunManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_resource_meun_manage.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_resource_meun_manage.menu_id
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_resource_meun_manage.resources_id
     *
     * @mbggenerated
     */
    private Integer resourcesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_resource_meun_manage.id
     *
     * @return the value of loan_resource_meun_manage.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_resource_meun_manage.id
     *
     * @param id the value for loan_resource_meun_manage.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_resource_meun_manage.menu_id
     *
     * @return the value of loan_resource_meun_manage.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_resource_meun_manage.menu_id
     *
     * @param menuId the value for loan_resource_meun_manage.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_resource_meun_manage.resources_id
     *
     * @return the value of loan_resource_meun_manage.resources_id
     *
     * @mbggenerated
     */
    public Integer getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_resource_meun_manage.resources_id
     *
     * @param resourcesId the value for loan_resource_meun_manage.resources_id
     *
     * @mbggenerated
     */
    public void setResourcesId(Integer resourcesId) {
        this.resourcesId = resourcesId;
    }
}