package com.xiaochong.loan.background.entity.po;

import java.util.Date;

public class ResourcesManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_resources_manage.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_resources_manage.res_name
     *
     * @mbggenerated
     */
    private String resName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_resources_manage.res_url
     *
     * @mbggenerated
     */
    private String resUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_resources_manage.res_remark
     *
     * @mbggenerated
     */
    private String resRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_resources_manage.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_resources_manage.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_resources_manage.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_resources_manage.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_resources_manage.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_resources_manage.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_resources_manage.id
     *
     * @return the value of loan_resources_manage.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_resources_manage.id
     *
     * @param id the value for loan_resources_manage.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_resources_manage.res_name
     *
     * @return the value of loan_resources_manage.res_name
     *
     * @mbggenerated
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_resources_manage.res_name
     *
     * @param resName the value for loan_resources_manage.res_name
     *
     * @mbggenerated
     */
    public void setResName(String resName) {
        this.resName = resName == null ? null : resName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_resources_manage.res_url
     *
     * @return the value of loan_resources_manage.res_url
     *
     * @mbggenerated
     */
    public String getResUrl() {
        return resUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_resources_manage.res_url
     *
     * @param resUrl the value for loan_resources_manage.res_url
     *
     * @mbggenerated
     */
    public void setResUrl(String resUrl) {
        this.resUrl = resUrl == null ? null : resUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_resources_manage.res_remark
     *
     * @return the value of loan_resources_manage.res_remark
     *
     * @mbggenerated
     */
    public String getResRemark() {
        return resRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_resources_manage.res_remark
     *
     * @param resRemark the value for loan_resources_manage.res_remark
     *
     * @mbggenerated
     */
    public void setResRemark(String resRemark) {
        this.resRemark = resRemark == null ? null : resRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_resources_manage.status
     *
     * @return the value of loan_resources_manage.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_resources_manage.status
     *
     * @param status the value for loan_resources_manage.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_resources_manage.type
     *
     * @return the value of loan_resources_manage.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_resources_manage.type
     *
     * @param type the value for loan_resources_manage.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_resources_manage.parent_id
     *
     * @return the value of loan_resources_manage.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_resources_manage.parent_id
     *
     * @param parentId the value for loan_resources_manage.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_resources_manage.sort
     *
     * @return the value of loan_resources_manage.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_resources_manage.sort
     *
     * @param sort the value for loan_resources_manage.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_resources_manage.updatetime
     *
     * @return the value of loan_resources_manage.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_resources_manage.updatetime
     *
     * @param updatetime the value for loan_resources_manage.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_resources_manage.createtime
     *
     * @return the value of loan_resources_manage.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_resources_manage.createtime
     *
     * @param createtime the value for loan_resources_manage.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}