package com.xiaochong.loan.background.entity.po;

import java.util.Date;

public class RiskReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_risk_report.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_risk_report.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_risk_report.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_risk_report.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_risk_report.creditReport
     *
     * @mbggenerated
     */
    private String creditreport;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_risk_report.id
     *
     * @return the value of loan_risk_report.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_risk_report.id
     *
     * @param id the value for loan_risk_report.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_risk_report.order_no
     *
     * @return the value of loan_risk_report.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_risk_report.order_no
     *
     * @param orderNo the value for loan_risk_report.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_risk_report.id_card
     *
     * @return the value of loan_risk_report.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_risk_report.id_card
     *
     * @param idCard the value for loan_risk_report.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_risk_report.create_time
     *
     * @return the value of loan_risk_report.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_risk_report.create_time
     *
     * @param createTime the value for loan_risk_report.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_risk_report.creditReport
     *
     * @return the value of loan_risk_report.creditReport
     *
     * @mbggenerated
     */
    public String getCreditreport() {
        return creditreport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_risk_report.creditReport
     *
     * @param creditreport the value for loan_risk_report.creditReport
     *
     * @mbggenerated
     */
    public void setCreditreport(String creditreport) {
        this.creditreport = creditreport == null ? null : creditreport.trim();
    }
}