package com.xiaochong.loan.background.entity.po;

public class RoleResourcesManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_role_resources_manage.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_role_resources_manage.resources_id
     *
     * @mbggenerated
     */
    private Integer resourcesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_role_resources_manage.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_role_resources_manage.id
     *
     * @return the value of loan_role_resources_manage.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_role_resources_manage.id
     *
     * @param id the value for loan_role_resources_manage.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_role_resources_manage.resources_id
     *
     * @return the value of loan_role_resources_manage.resources_id
     *
     * @mbggenerated
     */
    public Integer getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_role_resources_manage.resources_id
     *
     * @param resourcesId the value for loan_role_resources_manage.resources_id
     *
     * @mbggenerated
     */
    public void setResourcesId(Integer resourcesId) {
        this.resourcesId = resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_role_resources_manage.role_id
     *
     * @return the value of loan_role_resources_manage.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_role_resources_manage.role_id
     *
     * @param roleId the value for loan_role_resources_manage.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}