package com.xiaochong.loan.background.entity.po;

import java.util.Date;

public class RoleManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_role_manage.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_role_manage.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_role_manage.role_remark
     *
     * @mbggenerated
     */
    private String roleRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_role_manage.status
     *
     * @mbggenerated
     */
    private String status = "1";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_role_manage.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_role_manage.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_role_manage.id
     *
     * @return the value of loan_role_manage.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_role_manage.id
     *
     * @param id the value for loan_role_manage.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_role_manage.role_name
     *
     * @return the value of loan_role_manage.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_role_manage.role_name
     *
     * @param roleName the value for loan_role_manage.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_role_manage.role_remark
     *
     * @return the value of loan_role_manage.role_remark
     *
     * @mbggenerated
     */
    public String getRoleRemark() {
        return roleRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_role_manage.role_remark
     *
     * @param roleRemark the value for loan_role_manage.role_remark
     *
     * @mbggenerated
     */
    public void setRoleRemark(String roleRemark) {
        this.roleRemark = roleRemark == null ? null : roleRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_role_manage.status
     *
     * @return the value of loan_role_manage.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_role_manage.status
     *
     * @param status the value for loan_role_manage.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_role_manage.updatetime
     *
     * @return the value of loan_role_manage.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_role_manage.updatetime
     *
     * @param updatetime the value for loan_role_manage.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_role_manage.createtime
     *
     * @return the value of loan_role_manage.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_role_manage.createtime
     *
     * @param createtime the value for loan_role_manage.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    @Override
    public String toString() {
        return "RoleManage{" +
                "id=" + id +
                ", roleName='" + roleName + '\'' +
                ", roleRemark='" + roleRemark + '\'' +
                ", status='" + status + '\'' +
                ", updatetime=" + updatetime +
                ", createtime=" + createtime +
                '}';
    }
}