package com.xiaochong.loan.background.entity.po;

import java.util.Date;

public class SmsTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_sms_template.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_sms_template.merch_id
     *
     * @mbggenerated
     */
    private Integer merchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_sms_template.status
     *
     * @mbggenerated
     */
    private String status = "1";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_sms_template.send_status
     *
     * @mbggenerated
     */
    private String sendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_sms_template.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_sms_template.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_sms_template.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_sms_template.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_sms_template.id
     *
     * @return the value of loan_sms_template.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_sms_template.id
     *
     * @param id the value for loan_sms_template.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_sms_template.merch_id
     *
     * @return the value of loan_sms_template.merch_id
     *
     * @mbggenerated
     */
    public Integer getMerchId() {
        return merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_sms_template.merch_id
     *
     * @param merchId the value for loan_sms_template.merch_id
     *
     * @mbggenerated
     */
    public void setMerchId(Integer merchId) {
        this.merchId = merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_sms_template.status
     *
     * @return the value of loan_sms_template.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_sms_template.status
     *
     * @param status the value for loan_sms_template.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_sms_template.send_status
     *
     * @return the value of loan_sms_template.send_status
     *
     * @mbggenerated
     */
    public String getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_sms_template.send_status
     *
     * @param sendStatus the value for loan_sms_template.send_status
     *
     * @mbggenerated
     */
    public void setSendStatus(String sendStatus) {
        this.sendStatus = sendStatus == null ? null : sendStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_sms_template.update_user
     *
     * @return the value of loan_sms_template.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_sms_template.update_user
     *
     * @param updateUser the value for loan_sms_template.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_sms_template.createtime
     *
     * @return the value of loan_sms_template.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_sms_template.createtime
     *
     * @param createtime the value for loan_sms_template.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_sms_template.updatetime
     *
     * @return the value of loan_sms_template.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_sms_template.updatetime
     *
     * @param updatetime the value for loan_sms_template.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_sms_template.content
     *
     * @return the value of loan_sms_template.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_sms_template.content
     *
     * @param content the value for loan_sms_template.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}