package com.xiaochong.loan.background.entity.po;

import java.util.Date;

public class UrgeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_record.urge_over_due_id
     *
     * @mbggenerated
     */
    private Integer urgeOverDueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_record.stage_no
     *
     * @mbggenerated
     */
    private Integer stageNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_record.urge_content
     *
     * @mbggenerated
     */
    private String urgeContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_record.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_record.id
     *
     * @return the value of loan_urge_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_record.id
     *
     * @param id the value for loan_urge_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_record.urge_over_due_id
     *
     * @return the value of loan_urge_record.urge_over_due_id
     *
     * @mbggenerated
     */
    public Integer getUrgeOverDueId() {
        return urgeOverDueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_record.urge_over_due_id
     *
     * @param urgeOverDueId the value for loan_urge_record.urge_over_due_id
     *
     * @mbggenerated
     */
    public void setUrgeOverDueId(Integer urgeOverDueId) {
        this.urgeOverDueId = urgeOverDueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_record.stage_no
     *
     * @return the value of loan_urge_record.stage_no
     *
     * @mbggenerated
     */
    public Integer getStageNo() {
        return stageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_record.stage_no
     *
     * @param stageNo the value for loan_urge_record.stage_no
     *
     * @mbggenerated
     */
    public void setStageNo(Integer stageNo) {
        this.stageNo = stageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_record.urge_content
     *
     * @return the value of loan_urge_record.urge_content
     *
     * @mbggenerated
     */
    public String getUrgeContent() {
        return urgeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_record.urge_content
     *
     * @param urgeContent the value for loan_urge_record.urge_content
     *
     * @mbggenerated
     */
    public void setUrgeContent(String urgeContent) {
        this.urgeContent = urgeContent == null ? null : urgeContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_record.create_user
     *
     * @return the value of loan_urge_record.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_record.create_user
     *
     * @param createUser the value for loan_urge_record.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_record.create_time
     *
     * @return the value of loan_urge_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_record.create_time
     *
     * @param createTime the value for loan_urge_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return "UrgeRecord{" +
                "id=" + id +
                ", urgeOverDueId=" + urgeOverDueId +
                ", stageNo=" + stageNo +
                ", urgeContent='" + urgeContent + '\'' +
                ", createUser=" + createUser +
                ", createTime=" + createTime +
                '}';
    }
}