package com.xiaochong.loan.background.entity.po;

import java.math.BigDecimal;
import java.util.Date;

public class UrgeOverdue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_overdue.id
     *
     * @mbggenerated
     */
    private Integer id;

    private Integer merchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_overdue.borrower_id
     *
     * @mbggenerated
     */
    private Integer borrowerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_overdue.borrower_name
     *
     * @mbggenerated
     */
    private String borrowerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_overdue.borrower_phone
     *
     * @mbggenerated
     */
    private String borrowerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_overdue.overdue_num
     *
     * @mbggenerated
     */
    private Integer overdueNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_overdue.overdue_all_money
     *
     * @mbggenerated
     */
    private BigDecimal overdueAllMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_overdue.last_follow_id
     *
     * @mbggenerated
     */
    private Integer lastFollowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_overdue.last_follow_time
     *
     * @mbggenerated
     */
    private Date lastFollowTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_overdue.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_overdue.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_overdue.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_overdue.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_urge_overdue.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    private Integer maxOverdueDays;

    private Integer applicationId;

    public Integer getApplicationId() {
        return applicationId;
    }

    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    public Integer getMerchId() {
        return merchId;
    }

    public void setMerchId(Integer merchId) {
        this.merchId = merchId;
    }

    public Integer getMaxOverdueDays() {
        return maxOverdueDays;
    }

    public void setMaxOverdueDays(Integer maxOverdueDays) {
        this.maxOverdueDays = maxOverdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_overdue.id
     *
     * @return the value of loan_urge_overdue.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_overdue.id
     *
     * @param id the value for loan_urge_overdue.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_overdue.borrower_id
     *
     * @return the value of loan_urge_overdue.borrower_id
     *
     * @mbggenerated
     */
    public Integer getBorrowerId() {
        return borrowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_overdue.borrower_id
     *
     * @param borrowerId the value for loan_urge_overdue.borrower_id
     *
     * @mbggenerated
     */
    public void setBorrowerId(Integer borrowerId) {
        this.borrowerId = borrowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_overdue.borrower_name
     *
     * @return the value of loan_urge_overdue.borrower_name
     *
     * @mbggenerated
     */
    public String getBorrowerName() {
        return borrowerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_overdue.borrower_name
     *
     * @param borrowerName the value for loan_urge_overdue.borrower_name
     *
     * @mbggenerated
     */
    public void setBorrowerName(String borrowerName) {
        this.borrowerName = borrowerName == null ? null : borrowerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_overdue.borrower_phone
     *
     * @return the value of loan_urge_overdue.borrower_phone
     *
     * @mbggenerated
     */
    public String getBorrowerPhone() {
        return borrowerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_overdue.borrower_phone
     *
     * @param borrowerPhone the value for loan_urge_overdue.borrower_phone
     *
     * @mbggenerated
     */
    public void setBorrowerPhone(String borrowerPhone) {
        this.borrowerPhone = borrowerPhone == null ? null : borrowerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_overdue.overdue_num
     *
     * @return the value of loan_urge_overdue.overdue_num
     *
     * @mbggenerated
     */
    public Integer getOverdueNum() {
        return overdueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_overdue.overdue_num
     *
     * @param overdueNum the value for loan_urge_overdue.overdue_num
     *
     * @mbggenerated
     */
    public void setOverdueNum(Integer overdueNum) {
        this.overdueNum = overdueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_overdue.overdue_all_money
     *
     * @return the value of loan_urge_overdue.overdue_all_money
     *
     * @mbggenerated
     */
    public BigDecimal getOverdueAllMoney() {
        return overdueAllMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_overdue.overdue_all_money
     *
     * @param overdueAllMoney the value for loan_urge_overdue.overdue_all_money
     *
     * @mbggenerated
     */
    public void setOverdueAllMoney(BigDecimal overdueAllMoney) {
        this.overdueAllMoney = overdueAllMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_overdue.last_follow_id
     *
     * @return the value of loan_urge_overdue.last_follow_id
     *
     * @mbggenerated
     */
    public Integer getLastFollowId() {
        return lastFollowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_overdue.last_follow_id
     *
     * @param lastFollowId the value for loan_urge_overdue.last_follow_id
     *
     * @mbggenerated
     */
    public void setLastFollowId(Integer lastFollowId) {
        this.lastFollowId = lastFollowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_overdue.last_follow_time
     *
     * @return the value of loan_urge_overdue.last_follow_time
     *
     * @mbggenerated
     */
    public Date getLastFollowTime() {
        return lastFollowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_overdue.last_follow_time
     *
     * @param lastFollowTime the value for loan_urge_overdue.last_follow_time
     *
     * @mbggenerated
     */
    public void setLastFollowTime(Date lastFollowTime) {
        this.lastFollowTime = lastFollowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_overdue.status
     *
     * @return the value of loan_urge_overdue.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_overdue.status
     *
     * @param status the value for loan_urge_overdue.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_overdue.create_user
     *
     * @return the value of loan_urge_overdue.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_overdue.create_user
     *
     * @param createUser the value for loan_urge_overdue.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_overdue.create_time
     *
     * @return the value of loan_urge_overdue.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_overdue.create_time
     *
     * @param createTime the value for loan_urge_overdue.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_overdue.update_user
     *
     * @return the value of loan_urge_overdue.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_overdue.update_user
     *
     * @param updateUser the value for loan_urge_overdue.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_urge_overdue.update_time
     *
     * @return the value of loan_urge_overdue.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_urge_overdue.update_time
     *
     * @param updateTime the value for loan_urge_overdue.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "UrgeOverdue{" +
                "id=" + id +
                ", merchId=" + merchId +
                ", borrowerId=" + borrowerId +
                ", borrowerName='" + borrowerName + '\'' +
                ", borrowerPhone='" + borrowerPhone + '\'' +
                ", overdueNum=" + overdueNum +
                ", overdueAllMoney=" + overdueAllMoney +
                ", lastFollowId=" + lastFollowId +
                ", lastFollowTime=" + lastFollowTime +
                ", status='" + status + '\'' +
                ", createUser=" + createUser +
                ", createTime=" + createTime +
                ", updateUser=" + updateUser +
                ", updateTime=" + updateTime +
                ", maxOverdueDays=" + maxOverdueDays +
                ", applicationId=" + applicationId +
                '}';
    }
}