package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.BankCard;

import java.util.List;

public interface BankCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_bank_card
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_bank_card
     *
     * @mbggenerated
     */
    int insert(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_bank_card
     *
     * @mbggenerated
     */
    int insertSelective(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_bank_card
     *
     * @mbggenerated
     */
    BankCard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_bank_card
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_bank_card
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BankCard record);

    BankCard getByBankCard(BankCard loanBankCard);

    List<BankCard> selectByBankCard(BankCard bankCardForSearch);
}