package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.BorrowerBalance;
import org.apache.ibatis.annotations.Param;

public interface BorrowerBalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_borrower_balance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_borrower_balance
     *
     * @mbggenerated
     */
    int insert(BorrowerBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_borrower_balance
     *
     * @mbggenerated
     */
    int insertSelective(BorrowerBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_borrower_balance
     *
     * @mbggenerated
     */
    BorrowerBalance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_borrower_balance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BorrowerBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_borrower_balance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BorrowerBalance record);

    BorrowerBalance selectBorrowerBalanceByBorrowerId(@Param("borrowerId") Integer borrowerId);
}