package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.EducationInfo;

public interface EducationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_education_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_education_info
     *
     * @mbggenerated
     */
    int insert(EducationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_education_info
     *
     * @mbggenerated
     */
    int insertSelective(EducationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_education_info
     *
     * @mbggenerated
     */
    EducationInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_education_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EducationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_education_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EducationInfo record);

    EducationInfo getByEducationInfo(EducationInfo loanEducationinfo);
}