package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.FlowOption;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FlowOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_flow_option
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_flow_option
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    int insert(FlowOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_flow_option
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    int insertSelective(FlowOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_flow_option
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    FlowOption selectByPrimaryKey(Integer id);

    List<FlowOption> selectFlowOption(FlowOption flowOption);

    FlowOption selectOneFlowOption(FlowOption flowOption);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_flow_option
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    int updateByPrimaryKeySelective(FlowOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_flow_option
     *
     * @mbggenerated Fri Aug 11 19:43:59 CST 2017
     */
    int updateByPrimaryKey(FlowOption record);

    FlowOption selectOneByFlowOptionNo(@Param("flowOptionNo") String flowOptionNo);


    List<FlowOption> selectByFlowOptionNoList(List<String> flowOptionNoList);
}