package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.ManageAdmin;
import com.xiaochong.loan.background.entity.vo.ManagerAdminVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ManageAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_manage_admin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_manage_admin
     *
     * @mbggenerated
     */
    int insert(ManageAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_manage_admin
     *
     * @mbggenerated
     */
    int insertSelective(ManageAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_manage_admin
     *
     * @mbggenerated
     */
    ManageAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_manage_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_manage_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManageAdmin record);

    ManageAdmin getByManageAdmin(ManageAdmin manageAdmin);

    List<ManagerAdminVo> manageAdminPage();
}