package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.MerchantSubmitProject;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MerchantSubmitProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_submit_project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_submit_project
     *
     * @mbggenerated
     */
    int insert(MerchantSubmitProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_submit_project
     *
     * @mbggenerated
     */
    int insertSelective(MerchantSubmitProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_submit_project
     *
     * @mbggenerated
     */
    MerchantSubmitProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_submit_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MerchantSubmitProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_submit_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MerchantSubmitProject record);

    List<MerchantSubmitProject> selectMerchantSubmitProject(MerchantSubmitProject merchantSubmitProject);

    int selectCountMerchantSubmitProjectByAppId(Integer applicationId);
}