package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.MerchDataTemplate;

import java.util.List;

public interface MerchDataTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merch_data_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merch_data_template
     *
     * @mbggenerated
     */
    int insert(MerchDataTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merch_data_template
     *
     * @mbggenerated
     */
    int insertSelective(MerchDataTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merch_data_template
     *
     * @mbggenerated
     */
    MerchDataTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merch_data_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MerchDataTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merch_data_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MerchDataTemplate record);

    List<MerchDataTemplate> searchMerchDataTemplate(MerchDataTemplate merchDataTemplate);
}