package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.MerchantAuditData;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MerchantAuditDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_audit_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_audit_data
     *
     * @mbggenerated
     */
    int insert(MerchantAuditData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_audit_data
     *
     * @mbggenerated
     */
    int insertSelective(MerchantAuditData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_audit_data
     *
     * @mbggenerated
     */
    MerchantAuditData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_audit_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MerchantAuditData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_audit_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MerchantAuditData record);

    List<MerchantAuditData> selectMerchantAuditData(MerchantAuditData merchantAuditData);

    List<MerchantAuditData> selectMerchantAuditDataByApplicationId(@Param("applicationId") Integer applicationId);
}