package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.MerchantRecharge;

import java.util.List;

public interface MerchantRechargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_recharge
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_recharge
     *
     * @mbggenerated
     */
    int insert(MerchantRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_recharge
     *
     * @mbggenerated
     */
    int insertSelective(MerchantRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_recharge
     *
     * @mbggenerated
     */
    MerchantRecharge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_recharge
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MerchantRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_recharge
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MerchantRecharge record);

    List<MerchantRecharge> selectMerchantRecharge(MerchantRecharge merchantRecharge);
}