package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.MerchantSubmitData;

import java.util.List;

public interface MerchantSubmitDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_submit_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_submit_data
     *
     * @mbggenerated
     */
    int insert(MerchantSubmitData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_submit_data
     *
     * @mbggenerated
     */
    int insertSelective(MerchantSubmitData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_submit_data
     *
     * @mbggenerated
     */
    MerchantSubmitData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_submit_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MerchantSubmitData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_submit_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MerchantSubmitData record);

    List<MerchantSubmitData> selectMerchantSubmitData(MerchantSubmitData merchantSubmitData);

    List<MerchantSubmitData> selectMerchantSubmitDataByApplicationId(Integer applicationId);
}