package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.MerchantinfoCopy;

import java.util.List;

public interface MerchantinfoCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchantinfo_copy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String toid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchantinfo_copy
     *
     * @mbggenerated
     */
    int insert(MerchantinfoCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchantinfo_copy
     *
     * @mbggenerated
     */
    int insertSelective(MerchantinfoCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchantinfo_copy
     *
     * @mbggenerated
     */
    MerchantinfoCopy selectByPrimaryKey(String toid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchantinfo_copy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MerchantinfoCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchantinfo_copy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MerchantinfoCopy record);

    List<MerchantinfoCopy> listByMerchantinfoCopy(MerchantinfoCopy merchantinfoCopy);
}