package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.MerchantFlowOption;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MerchantFlowOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_flow_option
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_flow_option
     *
     * @mbggenerated
     */
    int insert(MerchantFlowOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_flow_option
     *
     * @mbggenerated
     */
    int insertSelective(MerchantFlowOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_flow_option
     *
     * @mbggenerated
     */
    MerchantFlowOption selectByPrimaryKey(Integer id);


    List<MerchantFlowOption> selectMerchantFlowOption(MerchantFlowOption merchantFlowOption);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_flow_option
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MerchantFlowOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_merchant_flow_option
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MerchantFlowOption record);

    int deleteByMerchIdAndFlowNo(MerchantFlowOption merchantFlowOption);

    void deleteByMerchId(@Param("merchId") Integer merchId);
}