package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.Order;
import com.xiaochong.loan.background.entity.vo.OrderWebappVo;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Order record);

    List<OrderWebappVo> getOrderWebappVoList(@Param("proxyUserId")String proxyUserId,
                                             @Param("merchId")Integer merchId,
                                             @Param("status")String[] status,
                                             @Param("searchStatus")String searchStatus,
                                             @Param("condition")String condition,
                                             @Param("startTime")Date startTime,
                                             @Param("endTime")Date endTime);


    Order selectOrderByToken(@Param("orderToken")String orderToken);

    Order getByOrder(Order order);

    List<Order> listByOrder(Order order);

    /**
     * 根据订单编号修改订单主体
     * @param order 订单主体
     * @return
     */
    int updateOrderByOrderNum(Order order);

    /**
     * 根据订单编号查询订单
     * @param orderNum 订单编号
     * @return 订单主体
     */
    Order selectOrderByOrderNum(String orderNum);
}