package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.OrderCopy;

import java.util.List;

public interface OrderCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_copy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String toid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_copy
     *
     * @mbggenerated
     */
    int insert(OrderCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_copy
     *
     * @mbggenerated
     */
    int insertSelective(OrderCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_copy
     *
     * @mbggenerated
     */
    OrderCopy selectByPrimaryKey(String toid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_copy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_copy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderCopy record);

    List<OrderCopy> listByOrderCopy(OrderCopy searchOrderCopy);
}