package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.OrderFlow;
import com.xiaochong.loan.background.entity.vo.OrderFlowBackVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_flow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_flow
     *
     * @mbggenerated
     */
    int insert(OrderFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_flow
     *
     * @mbggenerated
     */
    int insertSelective(OrderFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_flow
     *
     * @mbggenerated
     */
    OrderFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderFlow record);

    OrderFlow getByOrderFlow(OrderFlow orderFlow);


    /**
     * 查询订单下所有的认证记录
     * @param orderNum 订单编号
     * @return 订单认证记录集合
     */
    List<OrderFlow> selectFlowByOrderNum(@Param("orderNum")String orderNum);

    List<OrderFlow> listByOrderFlow(OrderFlow orderFlow);

    List<OrderFlowBackVo> getOrderFlowBackVoList(@Param("status")Integer status,
                                                 @Param("searchStatus")String searchStatus,
                                                 @Param("condition")String condition,
                                                 @Param("startTime")String startTime,
                                                 @Param("endTime")String endTime);
}