package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.OrderUserInfo;

public interface OrderUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_user_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_user_info
     *
     * @mbggenerated
     */
    int insert(OrderUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_user_info
     *
     * @mbggenerated
     */
    int insertSelective(OrderUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_user_info
     *
     * @mbggenerated
     */
    OrderUserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_order_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderUserInfo record);

    OrderUserInfo getByOrderUserInfo(OrderUserInfo orderUserInfo);
}