package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.ProxyUser;
import com.xiaochong.loan.background.entity.vo.ProxyUserVo;
import com.xiaochong.loan.background.entity.vo.SubUserWebappVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProxyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_proxy_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_proxy_user
     *
     * @mbggenerated
     */
    int insert(ProxyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_proxy_user
     *
     * @mbggenerated
     */
    int insertSelective(ProxyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_proxy_user
     *
     * @mbggenerated
     */
    ProxyUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_proxy_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProxyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_proxy_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProxyUser record);

    ProxyUser getByProxyUser(ProxyUser proxyUser);

    List<ProxyUser> selectProxyUser(ProxyUser proxyUser);

    void updatePorxyUserStatus(@Param("merchId") Integer merchId, @Param("type") String type, @Param("status") String status);

    List<SubUserWebappVo> pageProxyUserVo(@Param("merchId") Integer merchId, @Param("isMaster") String isMaster);

    List<ProxyUser> listByProxyUser(ProxyUser proxyUser);

    List<ProxyUserVo> proxyUserPage(@Param("merchId") Integer merchId,
                                    @Param("searchStatus") String searchStatus,
                                    @Param("condition") String condition,
                                    @Param("startTime") String startTime,
                                    @Param("endTime") String endTime);
}