package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.ProxyuserCopy;

import java.util.List;

public interface ProxyuserCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_proxyuser_copy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String toid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_proxyuser_copy
     *
     * @mbggenerated
     */
    int insert(ProxyuserCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_proxyuser_copy
     *
     * @mbggenerated
     */
    int insertSelective(ProxyuserCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_proxyuser_copy
     *
     * @mbggenerated
     */
    ProxyuserCopy selectByPrimaryKey(String toid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_proxyuser_copy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProxyuserCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_proxyuser_copy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProxyuserCopy record);

    List<ProxyuserCopy> listByProxyuserCopy(ProxyuserCopy proxyuserCopy);
}