package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.RateTemplate;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RateTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_rate_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_rate_template
     *
     * @mbggenerated
     */
    int insert(RateTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_rate_template
     *
     * @mbggenerated
     */
    int insertSelective(RateTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_rate_template
     *
     * @mbggenerated
     */
    RateTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_rate_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RateTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_rate_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RateTemplate record);


    List<RateTemplate> selectByMerId(@Param("merId")Integer merId);

    List<RateTemplate> selectRateTemplate(RateTemplate rateTemplate);
}