package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.RepaymentPlan;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface RepaymentPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_repayment_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_repayment_plan
     *
     * @mbggenerated
     */
    int insert(RepaymentPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_repayment_plan
     *
     * @mbggenerated
     */
    int insertSelective(RepaymentPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_repayment_plan
     *
     * @mbggenerated
     */
    RepaymentPlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_repayment_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RepaymentPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_repayment_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RepaymentPlan record);

    List<RepaymentPlan> selectRepaymentPlan(RepaymentPlan repaymentPlan);
    List<RepaymentPlan> selectRepaymentPlanRecord(RepaymentPlan repaymentPlan);

    List<RepaymentPlan> selectRepaymentPlanByApplicationId(@Param("applicationId") Integer applicationId);


    List<RepaymentPlan> listByApplicationIdStatus(@Param("applicationId")Integer applicationId, @Param("status")String status);

    List<RepaymentPlan> selectByLoanApplicationIds(@Param("loanApplicationIds")List<Integer> loanApplicationIds);

    List<RepaymentPlan> selectOverDueInfos();

    List<Map<String,Object>> selectOverDueStatistics();

    List<RepaymentPlan> selectListByRepaymentPlanRecord(RepaymentPlan repaymentPlanForSearch);

    Integer selectCountByRepaymentPlan(RepaymentPlan repaymentPlan);
}