package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.ReportLbsEvtInfo;

import java.util.List;

public interface ReportLbsEvtInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_lbs_evt_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_lbs_evt_info
     *
     * @mbggenerated
     */
    int insert(ReportLbsEvtInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_lbs_evt_info
     *
     * @mbggenerated
     */
    int insertSelective(ReportLbsEvtInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_lbs_evt_info
     *
     * @mbggenerated
     */
    ReportLbsEvtInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_lbs_evt_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportLbsEvtInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_lbs_evt_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportLbsEvtInfo record);

    List<ReportLbsEvtInfo> listByReportLbsEvtInfo(ReportLbsEvtInfo reportLbsEvtInfo);
}