package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.ReportCallRecord;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReportCallRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_call_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_call_record
     *
     * @mbggenerated
     */
    int insert(ReportCallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_call_record
     *
     * @mbggenerated
     */
    int insertSelective(ReportCallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_call_record
     *
     * @mbggenerated
     */
    ReportCallRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_call_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportCallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_call_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportCallRecord record);

    List<ReportCallRecord> selectByOrderNum(@Param("orderNum") String orderNum);


    ReportCallRecord selectByOrderNumAndPhone(@Param("orderNum")String orderNum,@Param("phone")String phone);
}