package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.ReportYysReportInfo;
import org.apache.ibatis.annotations.Param;

public interface ReportYysReportInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_yys_report_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_yys_report_info
     *
     * @mbggenerated
     */
    int insert(ReportYysReportInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_yys_report_info
     *
     * @mbggenerated
     */
    int insertSelective(ReportYysReportInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_yys_report_info
     *
     * @mbggenerated
     */
    ReportYysReportInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_yys_report_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportYysReportInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_yys_report_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportYysReportInfo record);

    ReportYysReportInfo selectByOrderNumAndName(@Param("orderNum")String orderNum,@Param("filedName")String filedName);
}