package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.ReportTongdunRule;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReportTongdunRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_tongdun_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_tongdun_rule
     *
     * @mbggenerated
     */
    int insert(ReportTongdunRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_tongdun_rule
     *
     * @mbggenerated
     */
    int insertSelective(ReportTongdunRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_tongdun_rule
     *
     * @mbggenerated
     */
    ReportTongdunRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_tongdun_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportTongdunRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_tongdun_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportTongdunRule record);


    /**
     * 根据订单查询
     * @param orderNum 订单编号
     * @return
     */
    List<ReportTongdunRule> selectByOrderNum(@Param("orderNum")String orderNum);


    ReportTongdunRule selectByOrderNumAndItemName(@Param("orderNum")String orderNum,@Param("itemName")String itemName);
}