package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.ReportYysInfo;

public interface ReportYysInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_yys_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_yys_info
     *
     * @mbggenerated
     */
    int insert(ReportYysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_yys_info
     *
     * @mbggenerated
     */
    int insertSelective(ReportYysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_yys_info
     *
     * @mbggenerated
     */
    ReportYysInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_yys_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportYysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_yys_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportYysInfo record);
}