package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.ReportBlackInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReportBlackInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_black_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_black_info
     *
     * @mbggenerated
     */
    int insert(ReportBlackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_black_info
     *
     * @mbggenerated
     */
    int insertSelective(ReportBlackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_black_info
     *
     * @mbggenerated
     */
    ReportBlackInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_black_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportBlackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_black_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportBlackInfo record);

    /**
     * 根据规则id查询所有风险项
     * @param ruleId 规则id
     * @return 风险项集合
     */
    List<ReportBlackInfo> selectByRuleId(@Param("ruleId") Integer ruleId);


    /**
     * 根据规则id和规则名称查询
     * @param ruleId 规则id
     * @param name 风险项名称
     * @return 风险项
     */
    ReportBlackInfo selectByRuleIdAndName(@Param("ruleId")Integer ruleId,@Param("name")String name);
}