package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.ReportContactRecord;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReportContactRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_contact_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_contact_record
     *
     * @mbggenerated
     */
    int insert(ReportContactRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_contact_record
     *
     * @mbggenerated
     */
    int insertSelective(ReportContactRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_contact_record
     *
     * @mbggenerated
     */
    ReportContactRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_contact_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportContactRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_contact_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportContactRecord record);


    List<ReportContactRecord> selectByOrderNum(@Param("orderNum")String orderNum);


    ReportContactRecord selectByOrderNumAndPhone(@Param("orderNum")String orderNum,@Param("phone")String phone);
}