package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.ReportUserInfo;
import org.apache.ibatis.annotations.Param;
import sun.rmi.transport.proxy.RMIHttpToPortSocketFactory;

public interface ReportUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_user_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_user_info
     *
     * @mbggenerated
     */
    int insert(ReportUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_user_info
     *
     * @mbggenerated
     */
    int insertSelective(ReportUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_user_info
     *
     * @mbggenerated
     */
    ReportUserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_report_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportUserInfo record);

    /**
     * 查询字段数据
     * @param orderNum 订单编号
     * @param filedName 字段名称
     * @return 报告详情
     */
    ReportUserInfo selectReportUserByOrderNumAndFiledName(@Param("orderNum")String orderNum,@Param("filedName")String filedName);

}