package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.ResourcesWebapp;
import com.xiaochong.loan.background.entity.vo.MenuWebappVo;
import com.xiaochong.loan.background.entity.vo.ResourcesWebappPage;
import com.xiaochong.loan.background.entity.vo.ResourcesWebappVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ResourcesWebappMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resources_webapp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resources_webapp
     *
     * @mbggenerated
     */
    int insert(ResourcesWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resources_webapp
     *
     * @mbggenerated
     */
    int insertSelective(ResourcesWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resources_webapp
     *
     * @mbggenerated
     */
    ResourcesWebapp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resources_webapp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ResourcesWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resources_webapp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ResourcesWebapp record);

    List<MenuWebappVo> queryResourcesUserSelect(@Param("userId")String userId,
                                         @Param("type")Integer type);

    List<MenuWebappVo> queryResourcesMerchSelect(@Param("merchId")Integer merchId,
                                                 @Param("type")Integer type);

    List<MenuWebappVo> queryResourcesRoleSelect(@Param("roleId")String roleId,
                                                 @Param("type")Integer type);

    List<ResourcesWebapp> listByResourcesWebapp(ResourcesWebapp resources);

    List<ResourcesWebapp> queryAllResources();

    List<ResourcesWebappPage> resourcesWebappPage(@Param("parentId") Integer parentId,
                                                  @Param("type") Integer type,
                                                  @Param("resName") String resName,
                                                  @Param("resUrl") String resUrl);

    List<ResourcesWebappVo> listResourcesWebapp(@Param("merchId")Integer merchId,@Param("type")Integer type);

    List<MenuWebappVo> queryMerchMenu(@Param("merchId")Integer merchId,
                                      @Param("roleId")Integer roleId,
                                      @Param("type")Integer type);


    List<ResourcesWebapp> queryResourcesByUser(@Param("userId")Integer userId, @Param("type")Integer type);

    List<ResourcesWebapp> queryResourcesByMerch(@Param("merchId")Integer merchId, @Param("type")Integer type);
}