package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.ResourceMeunWebapp;

import java.util.List;

public interface ResourceMeunWebappMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resource_meun_webapp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resource_meun_webapp
     *
     * @mbggenerated
     */
    int insert(ResourceMeunWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resource_meun_webapp
     *
     * @mbggenerated
     */
    int insertSelective(ResourceMeunWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resource_meun_webapp
     *
     * @mbggenerated
     */
    ResourceMeunWebapp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resource_meun_webapp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ResourceMeunWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resource_meun_webapp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ResourceMeunWebapp record);

    List<ResourceMeunWebapp> listByResourceMeunWebapp(ResourceMeunWebapp resourceMeunWebapp);
}