package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.ResourceMeunManage;

import java.util.List;

public interface ResourceMeunManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resource_meun_manage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resource_meun_manage
     *
     * @mbggenerated
     */
    int insert(ResourceMeunManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resource_meun_manage
     *
     * @mbggenerated
     */
    int insertSelective(ResourceMeunManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resource_meun_manage
     *
     * @mbggenerated
     */
    ResourceMeunManage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resource_meun_manage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ResourceMeunManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_resource_meun_manage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ResourceMeunManage record);

    List<ResourceMeunManage> listByResourceMeunManage(ResourceMeunManage resourceMeunWebapp);
}