package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.RiskReport;

public interface RiskReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_risk_report
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_risk_report
     *
     * @mbggenerated
     */
    int insert(RiskReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_risk_report
     *
     * @mbggenerated
     */
    int insertSelective(RiskReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_risk_report
     *
     * @mbggenerated
     */
    RiskReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_risk_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RiskReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_risk_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(RiskReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_risk_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RiskReport record);
}