package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.RoleResourcesWebapp;

import java.util.List;

public interface RoleResourcesWebappMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_resources_webapp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_resources_webapp
     *
     * @mbggenerated
     */
    int insert(RoleResourcesWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_resources_webapp
     *
     * @mbggenerated
     */
    int insertSelective(RoleResourcesWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_resources_webapp
     *
     * @mbggenerated
     */
    RoleResourcesWebapp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_resources_webapp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleResourcesWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_resources_webapp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleResourcesWebapp record);

    List<RoleResourcesWebapp> listByRoleResourcesWebapp(RoleResourcesWebapp roleResourcesWebapp);

    RoleResourcesWebapp getByRoleResourcesWebapp(RoleResourcesWebapp roleResourcesWebapp);
}