package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.RoleWebapp;
import com.xiaochong.loan.background.entity.vo.RoleWebappVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoleWebappMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_webapp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_webapp
     *
     * @mbggenerated
     */
    int insert(RoleWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_webapp
     *
     * @mbggenerated
     */
    int insertSelective(RoleWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_webapp
     *
     * @mbggenerated
     */
    RoleWebapp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_webapp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_webapp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleWebapp record);

    List<RoleWebappVo> roleWebappPage(@Param(value = "proxyUserId") String proxyUserId);

    RoleWebapp getByUserId(@Param(value = "userId")Integer userId);
}