package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.RoleResourcesManage;
import com.xiaochong.loan.background.entity.vo.RoleResourcesManageVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoleResourcesManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_resources_manage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_resources_manage
     *
     * @mbggenerated
     */
    int insert(RoleResourcesManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_resources_manage
     *
     * @mbggenerated
     */
    int insertSelective(RoleResourcesManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_resources_manage
     *
     * @mbggenerated
     */
    RoleResourcesManage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_resources_manage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleResourcesManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_role_resources_manage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleResourcesManage record);

    List<RoleResourcesManage> listByRoleResourcesManage(RoleResourcesManage roleResourcesManage);

    List<RoleResourcesManageVo> listRoleResourcesManageVo(@Param("roleId") Integer roleId,@Param("type") Integer type);
}