package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.SmsSendLog;
import org.apache.ibatis.annotations.Param;

public interface SmsSendLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_sms_send_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_sms_send_log
     *
     * @mbggenerated
     */
    int insert(SmsSendLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_sms_send_log
     *
     * @mbggenerated
     */
    int insertSelective(SmsSendLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_sms_send_log
     *
     * @mbggenerated
     */
    SmsSendLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_sms_send_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmsSendLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_sms_send_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SmsSendLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_sms_send_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmsSendLog record);

    long countByMerchIdMonth(@Param("merchId") Integer merchId);

    long countByMerchIdAll(@Param("merchId")Integer merchId);
}