package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.SmsTemplate;
import com.xiaochong.loan.background.entity.vo.SmaTemplateVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SmsTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_sms_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_sms_template
     *
     * @mbggenerated
     */
    int insert(SmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_sms_template
     *
     * @mbggenerated
     */
    int insertSelective(SmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_sms_template
     *
     * @mbggenerated
     */
    SmsTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_sms_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_sms_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_sms_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmsTemplate record);

    SmsTemplate getBySmsTemplate(SmsTemplate smsTemplate);

    List<SmaTemplateVo> smsTemplatePage(@Param("userId") Integer userId);
}