package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.UserRoleWebapp;

import java.util.List;

public interface UserRoleWebappMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_user_role_webapp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_user_role_webapp
     *
     * @mbggenerated
     */
    int insert(UserRoleWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_user_role_webapp
     *
     * @mbggenerated
     */
    int insertSelective(UserRoleWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_user_role_webapp
     *
     * @mbggenerated
     */
    UserRoleWebapp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_user_role_webapp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRoleWebapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_user_role_webapp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRoleWebapp record);

    UserRoleWebapp getByUserRoleWebapp(UserRoleWebapp userRoleWebapp);

    List<UserRoleWebapp> listByUserRoleWebapp(UserRoleWebapp userRoleWebapp);
}