package com.xiaochong.loan.background.mapper;

import com.xiaochong.loan.background.entity.po.UserRoleManage;

public interface UserRoleManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_user_role_manage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_user_role_manage
     *
     * @mbggenerated
     */
    int insert(UserRoleManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_user_role_manage
     *
     * @mbggenerated
     */
    int insertSelective(UserRoleManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_user_role_manage
     *
     * @mbggenerated
     */
    UserRoleManage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_user_role_manage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRoleManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_user_role_manage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRoleManage record);

    UserRoleManage getByUserRoleManage(UserRoleManage userRoleManage);
}